local MM2_ITEMS = {
    ["2015"] = { name = "2015", value = 0, category = "Common", id = "2015" },
    ["3"] = { name = "3", value = 0, category = "Common", id = "3" },
    ["8bit"] = { name = "8Bit", value = 0, category = "Common", id = "8bit" },
    ["abduction_k_2025"] = { name = "Abduction K 2025", value = 0, category = "Common", id = "abduction_k_2025" },
    ["abstract"] = { name = "Abstract", value = 0, category = "Common", id = "abstract" },
    ["ace"] = { name = "Ace", value = 0, category = "Common", id = "ace" },
    ["adurite"] = { name = "Adurite", value = 0, category = "Common", id = "adurite" },
    ["aduritegun"] = { name = "Aduritegun", value = 0, category = "Gun", id = "aduritegun" },
    ["aid"] = { name = "Aid", value = 0, category = "Common", id = "aid" },
    ["alex"] = { name = "Alex", value = 0, category = "Common", id = "alex" },
    ["aliens_g_2021"] = { name = "Aliens G 2021", value = 0, category = "Common", id = "aliens_g_2021" },
    ["americagun"] = { name = "Americagun", value = 0, category = "Vintage", id = "americagun" },
    ["americaneagle"] = { name = "Americaneagle", value = 0, category = "Vintage", id = "americaneagle" },
    ["americasword"] = { name = "Americasword", value = 0, category = "Vintage", id = "americasword" },
    ["amerilaser"] = { name = "Amerilaser", value = 25, category = "Godly", id = "amerilaser" },
    ["apoc_g_2022"] = { name = "Apoc G 2022", value = 0, category = "Common", id = "apoc_g_2022" },
    ["apoc_k_2022"] = { name = "Apoc K 2022", value = 0, category = "Common", id = "apoc_k_2022" },
    ["aqua"] = { name = "Aqua", value = 0, category = "Common", id = "aqua" },
    ["aquarium_g_2025"] = { name = "Aquarium G 2025", value = 0, category = "Common", id = "aquarium_g_2025" },
    ["aquarium_k_2025"] = { name = "Aquarium K 2025", value = 0, category = "Common", id = "aquarium_k_2025" },
    ["arctic_g_2022"] = { name = "Arctic G 2022", value = 0, category = "Common", id = "arctic_g_2022" },
    ["arctic_k_2022"] = { name = "Arctic K 2022", value = 0, category = "Common", id = "arctic_k_2022" },
    ["asteroid"] = { name = "Asteroid", value = 0, category = "Common", id = "asteroid" },
    ["aurora_g_2019"] = { name = "Aurora G 2019", value = 0, category = "Common", id = "aurora_g_2019" },
    ["aurora_g_2021"] = { name = "Aurora G 2021", value = 0, category = "Common", id = "aurora_g_2021" },
    ["aurora_k_2019"] = { name = "Aurora K 2019", value = 0, category = "Common", id = "aurora_k_2019" },
    ["aurora_k_2021"] = { name = "Aurora K 2021", value = 0, category = "Common", id = "aurora_k_2021" },
    ["auroragun"] = { name = "Auroragun", value = 0, category = "Gun", id = "auroragun" },
    ["auroraknife"] = { name = "Auroraknife", value = 0, category = "Knife", id = "auroraknife" },
    ["bacon"] = { name = "Bacon", value = 0, category = "Common", id = "bacon" },
    ["badger"] = { name = "Badger", value = 0, category = "Common", id = "badger" },
    ["bat"] = { name = "Bat", value = 0, category = "Pet", id = "bat" },
    ["batchroma"] = { name = "Batchroma", value = 0, category = "Chroma", id = "batchroma" },
    ["batfire"] = { name = "Batfire", value = 0, category = "Pet", id = "batfire" },
    ["bats"] = { name = "Bats", value = 0, category = "Pet", id = "bats" },
    ["bats_g_2024"] = { name = "Bats G 2024", value = 0, category = "Pet", id = "bats_g_2024" },
    ["bats_k_2020"] = { name = "Bats K 2020", value = 0, category = "Pet", id = "bats_k_2020" },
    ["bats_k_2024"] = { name = "Bats K 2024", value = 0, category = "Pet", id = "bats_k_2024" },
    ["bats_k_2025"] = { name = "Bats K 2025", value = 0, category = "Pet", id = "bats_k_2025" },
    ["batsg"] = { name = "Batsg", value = 0, category = "Pet", id = "batsg" },
    ["batsk"] = { name = "Batsk", value = 0, category = "Pet", id = "batsk" },
    ["battleaxe"] = { name = "Battleaxe", value = 0, category = "Knife", id = "battleaxe" },
    ["battleaxe2"] = { name = "Battleaxe2", value = 0, category = "Knife", id = "battleaxe2" },
    ["batwing"] = { name = "Batwing", value = 57, category = "Ancient", id = "batwing" },
    ["bauble"] = { name = "Bauble", value = 900, category = "Godly", id = "bauble" },
    ["baublechroma"] = { name = "Baublechroma", value = 0, category = "Godly", id = "baublechroma" },
    ["baubleknife"] = { name = "Baubleknife", value = 0, category = "Godly", id = "baubleknife" },
    ["baubleknifechroma"] = { name = "Baubleknifechroma", value = 0, category = "Godly", id = "baubleknifechroma" },
    ["beach_k_2023"] = { name = "Beach K 2023", value = 0, category = "Common", id = "beach_k_2023" },
    ["bear"] = { name = "Bear", value = 0, category = "Pet", id = "bear" },
    ["bearchroma"] = { name = "Bearchroma", value = 0, category = "Chroma", id = "bearchroma" },
    ["bearfire"] = { name = "Bearfire", value = 0, category = "Pet", id = "bearfire" },
    ["bells_k_2023"] = { name = "Bells K 2023", value = 0, category = "Common", id = "bells_k_2023" },
    ["bigkill"] = { name = "Bigkill", value = 0, category = "Common", id = "bigkill" },
    ["bio_k_2023"] = { name = "Bio K 2023", value = 0, category = "Common", id = "bio_k_2023" },
    ["bioblade"] = { name = "Bioblade", value = 10, category = "Knife", id = "bioblade" },
    ["biogun"] = { name = "Biogun", value = 0, category = "Gun", id = "biogun" },
    ["bit"] = { name = "Bit", value = 0, category = "Common", id = "bit" },
    ["blackcat"] = { name = "Blackcat", value = 0, category = "Pet", id = "blackcat" },
    ["blaster"] = { name = "Blaster", value = 20, category = "Godly", id = "blaster" },
    ["bleached"] = { name = "Bleached", value = 0, category = "Common", id = "bleached" },
    ["bleed"] = { name = "Bleed", value = 0, category = "Common", id = "bleed" },
    ["blizzard"] = { name = "Blizzard", value = 150, category = "Common", id = "blizzard" },
    ["blizzardchroma"] = { name = "Blizzardchroma", value = 0, category = "Chroma", id = "blizzardchroma" },
    ["bloodknife"] = { name = "Bloodknife", value = 0, category = "Vintage", id = "bloodknife" },
    ["bloom"] = { name = "Bloom", value = 205, category = "Godly", id = "bloom" },
    ["blossom"] = { name = "Blossom", value = 0, category = "Common", id = "blossom" },
    ["blossom_g"] = { name = "Blossom G", value = 0, category = "Common", id = "blossom_g" },
    ["bluecamo_k_2022"] = { name = "Bluecamo K 2022", value = 0, category = "Common", id = "bluecamo_k_2022" },
    ["bluep"] = { name = "Bluep", value = 0, category = "Common", id = "bluep" },
    ["bluepumpkin19"] = { name = "Bluepumpkin19", value = 0, category = "Common", id = "bluepumpkin19" },
    ["bluepumpkin2020"] = { name = "Bluepumpkin2020", value = 0, category = "Common", id = "bluepumpkin2020" },
    ["blueseer"] = { name = "Blueseer", value = 0, category = "Godly", id = "blueseer" },
    ["bluesteel"] = { name = "Bluesteel", value = 0, category = "Common", id = "bluesteel" },
    ["bluesteelgun"] = { name = "Bluesteelgun", value = 0, category = "Gun", id = "bluesteelgun" },
    ["boneblade"] = { name = "Boneblade", value = 7, category = "Knife", id = "boneblade" },
    ["bonebladechroma"] = { name = "Bonebladechroma", value = 0, category = "Chroma", id = "bonebladechroma" },
    ["bones"] = { name = "Bones", value = 0, category = "Common", id = "bones" },
    ["bones_k_2020"] = { name = "Bones K 2020", value = 0, category = "Common", id = "bones_k_2020" },
    ["bones_k_2022"] = { name = "Bones K 2022", value = 0, category = "Common", id = "bones_k_2022" },
    ["bones_k_2024"] = { name = "Bones K 2024", value = 0, category = "Common", id = "bones_k_2024" },
    ["bones2019"] = { name = "Bones2019", value = 0, category = "Common", id = "bones2019" },
    ["borders"] = { name = "Borders", value = 0, category = "Common", id = "borders" },
    ["brains"] = { name = "Brains", value = 0, category = "Common", id = "brains" },
    ["brains2019"] = { name = "Brains2019", value = 0, category = "Common", id = "brains2019" },
    ["branches"] = { name = "Branches", value = 0, category = "Common", id = "branches" },
    ["broken_k_2023"] = { name = "Broken K 2023", value = 0, category = "Common", id = "broken_k_2023" },
    ["brush"] = { name = "Brush", value = 0, category = "Common", id = "brush" },
    ["bunnies_k_2025"] = { name = "Bunnies K 2025", value = 0, category = "Common", id = "bunnies_k_2025" },
    ["bunny"] = { name = "Bunny", value = 0, category = "Pet", id = "bunny" },
    ["Bunny2023"] = { name = "Bunny2023", value = 0, category = "Common", id = "Bunny2023" },
    ["bunnychroma"] = { name = "Bunnychroma", value = 0, category = "Chroma", id = "bunnychroma" },
    ["bunnyfire"] = { name = "Bunnyfire", value = 0, category = "Pet", id = "bunnyfire" },
    ["butterflies_g_2025"] = { name = "Butterflies G 2025", value = 0, category = "Common", id = "butterflies_g_2025" },
    ["camo"] = { name = "Camo", value = 0, category = "Common", id = "camo" },
    ["camoknife"] = { name = "Camoknife", value = 0, category = "Knife", id = "camoknife" },
    ["candied_g_2022"] = { name = "Candied G 2022", value = 0, category = "Common", id = "candied_g_2022" },
    ["candied_k_2022"] = { name = "Candied K 2022", value = 0, category = "Common", id = "candied_k_2022" },
    ["candies"] = { name = "Candies", value = 0, category = "Common", id = "candies" },
    ["candies2017"] = { name = "Candies2017", value = 0, category = "Common", id = "candies2017" },
    ["candle_k_2020"] = { name = "Candle K 2020", value = 0, category = "Common", id = "candle_k_2020" },
    ["candleflame"] = { name = "Candleflame", value = 0, category = "Common", id = "candleflame" },
    ["candleflame_g_2024"] = { name = "Candleflame G 2024", value = 0, category = "Common", id = "candleflame_g_2024" },
    ["candleflamechroma"] = { name = "Candleflamechroma", value = 0, category = "Chroma", id = "candleflamechroma" },
    ["candles_k_2024"] = { name = "Candles K 2024", value = 0, category = "Common", id = "candles_k_2024" },
    ["candy"] = { name = "Candy", value = 0, category = "Common", id = "candy" },
    ["candycorn"] = { name = "Candycorn", value = 0, category = "Common", id = "candycorn" },
    ["candycorn_g_2020"] = { name = "Candycorn G 2020", value = 0, category = "Common", id = "candycorn_g_2020" },
    ["candycorn_g_2022"] = { name = "Candycorn G 2022", value = 0, category = "Common", id = "candycorn_g_2022" },
    ["candycorn_g_2024"] = { name = "Candycorn G 2024", value = 0, category = "Common", id = "candycorn_g_2024" },
    ["candycorn_g_2025"] = { name = "Candycorn G 2025", value = 0, category = "Common", id = "candycorn_g_2025" },
    ["candycorn_k_2020"] = { name = "Candycorn K 2020", value = 0, category = "Common", id = "candycorn_k_2020" },
    ["candycorn_k_2022"] = { name = "Candycorn K 2022", value = 0, category = "Common", id = "candycorn_k_2022" },
    ["candycorn_k_2024"] = { name = "Candycorn K 2024", value = 0, category = "Common", id = "candycorn_k_2024" },
    ["candycorn_k_2025"] = { name = "Candycorn K 2025", value = 0, category = "Common", id = "candycorn_k_2025" },
    ["candycorn2019"] = { name = "Candycorn2019", value = 0, category = "Common", id = "candycorn2019" },
    ["candyswirl_g_2019"] = { name = "Candyswirl G 2019", value = 0, category = "Common", id = "candyswirl_g_2019" },
    ["candyswirl_k_2019"] = { name = "Candyswirl K 2019", value = 0, category = "Common", id = "candyswirl_k_2019" },
    ["cane"] = { name = "Cane", value = 0, category = "Common", id = "cane" },
    ["cane_g_2018"] = { name = "Cane G 2018", value = 0, category = "Common", id = "cane_g_2018" },
    ["cane_g_2021"] = { name = "Cane G 2021", value = 0, category = "Common", id = "cane_g_2021" },
    ["cane_k_2018"] = { name = "Cane K 2018", value = 0, category = "Common", id = "cane_k_2018" },
    ["cane_k_2021"] = { name = "Cane K 2021", value = 0, category = "Common", id = "cane_k_2021" },
    ["canegun"] = { name = "Canegun", value = 0, category = "Gun", id = "canegun" },
    ["canes_g_2023"] = { name = "Canes G 2023", value = 0, category = "Common", id = "canes_g_2023" },
    ["canes_k_2023"] = { name = "Canes K 2023", value = 0, category = "Common", id = "canes_k_2023" },
    ["cardboard"] = { name = "Cardboard", value = 0, category = "Common", id = "cardboard" },
    ["carrot"] = { name = "Carrot", value = 0, category = "Common", id = "carrot" },
    ["carrot_g_2024"] = { name = "Carrot G 2024", value = 0, category = "Common", id = "carrot_g_2024" },
    ["carrot_k_2024"] = { name = "Carrot K 2024", value = 0, category = "Common", id = "carrot_k_2024" },
    ["carrots_k_2025"] = { name = "Carrots K 2025", value = 0, category = "Common", id = "carrots_k_2025" },
    ["carved_g_2020"] = { name = "Carved G 2020", value = 0, category = "Common", id = "carved_g_2020" },
    ["carved_k_2020"] = { name = "Carved K 2020", value = 0, category = "Common", id = "carved_k_2020" },
    ["cat"] = { name = "Cat", value = 0, category = "Pet", id = "cat" },
    ["cat_g_2021"] = { name = "Cat G 2021", value = 0, category = "Pet", id = "cat_g_2021" },
    ["catchroma"] = { name = "Catchroma", value = 0, category = "Chroma", id = "catchroma" },
    ["catfire"] = { name = "Catfire", value = 0, category = "Pet", id = "catfire" },
    ["caution"] = { name = "Caution", value = 0, category = "Common", id = "caution" },
    ["cavern_g_2019"] = { name = "Cavern G 2019", value = 0, category = "Common", id = "cavern_g_2019" },
    ["cavern_k_2019"] = { name = "Cavern K 2019", value = 0, category = "Common", id = "cavern_k_2019" },
    ["celestial"] = { name = "Celestial", value = 1775, category = "Ancient", id = "celestial" },
    ["checker"] = { name = "Checker", value = 0, category = "Common", id = "checker" },
    ["cheddar"] = { name = "Cheddar", value = 0, category = "Common", id = "cheddar" },
    ["cheesy"] = { name = "Cheesy", value = 0, category = "Common", id = "cheesy" },
    ["cherry"] = { name = "Cherry", value = 0, category = "Common", id = "cherry" },
    ["chick_k_2025"] = { name = "Chick K 2025", value = 0, category = "Common", id = "chick_k_2025" },
    ["chill"] = { name = "Chill", value = 10, category = "Godly", id = "chill" },
    ["chilly"] = { name = "Chilly", value = 0, category = "Godly", id = "chilly" },
    ["chips"] = { name = "Chips", value = 0, category = "Common", id = "chips" },
    ["choco"] = { name = "Choco", value = 0, category = "Common", id = "choco" },
    ["chromadarkbringer"] = { name = "Chromadarkbringer", value = 0, category = "Godly", id = "chromadarkbringer" },
    ["chromalightbringer"] = { name = "Chromalightbringer", value = 0, category = "Godly", id = "chromalightbringer" },
    ["chromatic_g_2023"] = { name = "Chromatic G 2023", value = 0, category = "Chroma", id = "chromatic_g_2023" },
    ["chromatic_k_2023"] = { name = "Chromatic K 2023", value = 0, category = "Chroma", id = "chromatic_k_2023" },
    ["circuit"] = { name = "Circuit", value = 0, category = "Common", id = "circuit" },
    ["clan"] = { name = "Clan", value = 0, category = "Common", id = "clan" },
    ["clockwork"] = { name = "Clockwork", value = 10, category = "Godly", id = "clockwork" },
    ["clown"] = { name = "Clown", value = 0, category = "Common", id = "clown" },
    ["clown_g"] = { name = "Clown G", value = 0, category = "Common", id = "clown_g" },
    ["clown_g_2024"] = { name = "Clown G 2024", value = 0, category = "Common", id = "clown_g_2024" },
    ["clownfish_g_2024"] = { name = "Clownfish G 2024", value = 0, category = "Common", id = "clownfish_g_2024" },
    ["clownfish_k_2024"] = { name = "Clownfish K 2024", value = 0, category = "Common", id = "clownfish_k_2024" },
    ["coal"] = { name = "Coal", value = 0, category = "Common", id = "coal" },
    ["coal_g_2018"] = { name = "Coal G 2018", value = 0, category = "Common", id = "coal_g_2018" },
    ["coal_g_2021"] = { name = "Coal G 2021", value = 0, category = "Common", id = "coal_g_2021" },
    ["coal_g_2022"] = { name = "Coal G 2022", value = 0, category = "Common", id = "coal_g_2022" },
    ["coal_k_2018"] = { name = "Coal K 2018", value = 0, category = "Common", id = "coal_k_2018" },
    ["coal_k_2021"] = { name = "Coal K 2021", value = 0, category = "Common", id = "coal_k_2021" },
    ["coal_k_2022"] = { name = "Coal K 2022", value = 0, category = "Common", id = "coal_k_2022" },
    ["coconut_k_2025"] = { name = "Coconut K 2025", value = 0, category = "Common", id = "coconut_k_2025" },
    ["cola"] = { name = "Cola", value = 0, category = "Common", id = "cola" },
    ["cold"] = { name = "Cold", value = 0, category = "Common", id = "cold" },
    ["combat"] = { name = "Combat", value = 0, category = "Pet", id = "combat" },
    ["combat2"] = { name = "Combat2", value = 0, category = "Pet", id = "combat2" },
    ["constellation"] = { name = "Constellation", value = 3300, category = "Common", id = "constellation" },
    ["constellation_g_2024"] = { name = "Constellation G 2024", value = 0, category = "Common", id = "constellation_g_2024" },
    ["constellation_k_2024"] = { name = "Constellation K 2024", value = 0, category = "Common", id = "constellation_k_2024" },
    ["constellationchroma"] = { name = "Constellationchroma", value = 0, category = "Chroma", id = "constellationchroma" },
    ["cookie_g_2021"] = { name = "Cookie G 2021", value = 0, category = "Common", id = "cookie_g_2021" },
    ["cookie_k_2021"] = { name = "Cookie K 2021", value = 0, category = "Common", id = "cookie_k_2021" },
    ["cookieblade"] = { name = "Cookieblade", value = 3, category = "Godly", id = "cookieblade" },
    ["copper"] = { name = "Copper", value = 0, category = "Common", id = "copper" },
    ["corl"] = { name = "Corl", value = 0, category = "Common", id = "corl" },
    ["cottoncandy"] = { name = "Cottoncandy", value = 0, category = "Common", id = "cottoncandy" },
    ["cracks_g_2021"] = { name = "Cracks G 2021", value = 0, category = "Common", id = "cracks_g_2021" },
    ["cracks_k_2021"] = { name = "Cracks K 2021", value = 0, category = "Common", id = "cracks_k_2021" },
    ["cursed_g_2024"] = { name = "Cursed G 2024", value = 0, category = "Common", id = "cursed_g_2024" },
    ["cursed_k_2024"] = { name = "Cursed K 2024", value = 0, category = "Common", id = "cursed_k_2024" },
    ["damp"] = { name = "Damp", value = 0, category = "Common", id = "damp" },
    ["dark_g_2023"] = { name = "Dark G 2023", value = 0, category = "Common", id = "dark_g_2023" },
    ["dark_k_2023"] = { name = "Dark K 2023", value = 0, category = "Common", id = "dark_k_2023" },
    ["darkbringer"] = { name = "Darkbringer", value = 55, category = "Godly", id = "darkbringer" },
    ["darkness_g_2022"] = { name = "Darkness G 2022", value = 0, category = "Common", id = "darkness_g_2022" },
    ["darkness_k_2022"] = { name = "Darkness K 2022", value = 0, category = "Common", id = "darkness_k_2022" },
    ["darkshot"] = { name = "Darkshot", value = 0, category = "Gun", id = "darkshot" },
    ["darksword"] = { name = "Darksword", value = 0, category = "Knife", id = "darksword" },
    ["deathshard"] = { name = "Deathshard", value = 1, category = "Godly", id = "deathshard" },
    ["deathshardchroma"] = { name = "Deathshardchroma", value = 0, category = "Godly", id = "deathshardchroma" },
    ["deathspeaker"] = { name = "Deathspeaker", value = 0, category = "Common", id = "deathspeaker" },
    ["decorated_k_2025"] = { name = "Decorated K 2025", value = 0, category = "Common", id = "decorated_k_2025" },
    ["deepsea"] = { name = "Deepsea", value = 0, category = "Common", id = "deepsea" },
    ["denis"] = { name = "Denis", value = 0, category = "Common", id = "denis" },
    ["dew"] = { name = "Dew", value = 0, category = "Common", id = "dew" },
    ["disint"] = { name = "Disint", value = 0, category = "Common", id = "disint" },
    ["dog"] = { name = "Dog", value = 0, category = "Pet", id = "dog" },
    ["dogchroma"] = { name = "Dogchroma", value = 0, category = "Chroma", id = "dogchroma" },
    ["doge"] = { name = "Doge", value = 0, category = "Pet", id = "doge" },
    ["dogey"] = { name = "Dogey", value = 0, category = "Pet", id = "dogey" },
    ["dogfire"] = { name = "Dogfire", value = 0, category = "Pet", id = "dogfire" },
    ["dolphins_k_2025"] = { name = "Dolphins K 2025", value = 0, category = "Common", id = "dolphins_k_2025" },
    ["donut"] = { name = "Donut", value = 0, category = "Common", id = "donut" },
    ["doritos"] = { name = "Doritos", value = 0, category = "Common", id = "doritos" },
    ["dungeon"] = { name = "Dungeon", value = 0, category = "Common", id = "dungeon" },
    ["eclipse_k_2023"] = { name = "Eclipse K 2023", value = 0, category = "Common", id = "eclipse_k_2023" },
    ["eco"] = { name = "Eco", value = 0, category = "Common", id = "eco" },
    ["ecto"] = { name = "Ecto", value = 0, category = "Common", id = "ecto" },
    ["eggblade"] = { name = "Eggblade", value = 5, category = "Godly", id = "eggblade" },
    ["eggs"] = { name = "Eggs", value = 0, category = "Common", id = "eggs" },
    ["elderwoodgun"] = { name = "Elderwoodgun", value = 0, category = "Godly", id = "elderwoodgun" },
    ["elderwoodknife"] = { name = "Elderwoodknife", value = 0, category = "Knife", id = "elderwoodknife" },
    ["elderwoodknifechroma"] = { name = "Elderwoodknifechroma", value = 0, category = "Chroma", id = "elderwoodknifechroma" },
    ["elderwoodscythe"] = { name = "Elderwoodscythe", value = 0, category = "Ancient", id = "elderwoodscythe" },
    ["electro"] = { name = "Electro", value = 1, category = "Godly", id = "electro" },
    ["elf"] = { name = "Elf", value = 0, category = "Common", id = "elf" },
    ["elf_g_2023"] = { name = "Elf G 2023", value = 0, category = "Common", id = "elf_g_2023" },
    ["elf2017"] = { name = "Elf2017", value = 0, category = "Common", id = "elf2017" },
    ["elf2019"] = { name = "Elf2019", value = 0, category = "Common", id = "elf2019" },
    ["elfgun"] = { name = "Elfgun", value = 0, category = "Gun", id = "elfgun" },
    ["elfy"] = { name = "Elfy", value = 0, category = "Common", id = "elfy" },
    ["elite"] = { name = "Elite", value = 0, category = "Common", id = "elite" },
    ["eliteblue"] = { name = "Eliteblue", value = 0, category = "Common", id = "eliteblue" },
    ["elitegreen"] = { name = "Elitegreen", value = 0, category = "Common", id = "elitegreen" },
    ["elitey"] = { name = "Elitey", value = 0, category = "Common", id = "elitey" },
    ["emerald"] = { name = "Emerald", value = 0, category = "Common", id = "emerald" },
    ["energized_g_2025"] = { name = "Energized G 2025", value = 0, category = "Common", id = "energized_g_2025" },
    ["energized_k_2025"] = { name = "Energized K 2025", value = 0, category = "Common", id = "energized_k_2025" },
    ["engraved"] = { name = "Engraved", value = 0, category = "Common", id = "engraved" },
    ["eternal"] = { name = "Eternal", value = 8, category = "Godly", id = "eternal" },
    ["eternal2"] = { name = "Eternal2", value = 0, category = "Godly", id = "eternal2" },
    ["eternal3"] = { name = "Eternal3", value = 0, category = "Godly", id = "eternal3" },
    ["eternal4"] = { name = "Eternal4", value = 0, category = "Godly", id = "eternal4" },
    ["eternalcane"] = { name = "Eternalcane", value = 0, category = "Godly", id = "eternalcane" },
    ["euro"] = { name = "Euro", value = 0, category = "Common", id = "euro" },
    ["eye"] = { name = "Eye", value = 0, category = "Common", id = "eye" },
    ["eyeball_k_2022"] = { name = "Eyeball K 2022", value = 0, category = "Common", id = "eyeball_k_2022" },
    ["eyes_g_2020"] = { name = "Eyes G 2020", value = 0, category = "Common", id = "eyes_g_2020" },
    ["eyes_g_2025"] = { name = "Eyes G 2025", value = 0, category = "Common", id = "eyes_g_2025" },
    ["eyes_k_2020"] = { name = "Eyes K 2020", value = 0, category = "Common", id = "eyes_k_2020" },
    ["fade"] = { name = "Fade", value = 0, category = "Common", id = "fade" },
    ["fairy"] = { name = "Fairy", value = 0, category = "Common", id = "fairy" },
    ["fall_g_2025"] = { name = "Fall G 2025", value = 0, category = "Common", id = "fall_g_2025" },
    ["fallcamo_g_2021"] = { name = "Fallcamo G 2021", value = 0, category = "Common", id = "fallcamo_g_2021" },
    ["fallout"] = { name = "Fallout", value = 0, category = "Common", id = "fallout" },
    ["fang"] = { name = "Fang", value = 0, category = "Common", id = "fang" },
    ["fangchroma"] = { name = "Fangchroma", value = 0, category = "Chroma", id = "fangchroma" },
    ["fanta"] = { name = "Fanta", value = 0, category = "Common", id = "fanta" },
    ["fertilizerbox"] = { name = "Fertilizerbox", value = 0, category = "Common", id = "fertilizerbox" },
    ["fireplace_k_2023"] = { name = "Fireplace K 2023", value = 0, category = "Common", id = "fireplace_k_2023" },
    ["flames"] = { name = "Flames", value = 5, category = "Godly", id = "flames" },
    ["floatie_g_2024"] = { name = "Floatie G 2024", value = 0, category = "Common", id = "floatie_g_2024" },
    ["flora"] = { name = "Flora", value = 215, category = "Godly", id = "flora" },
    ["floral_g_2024"] = { name = "Floral G 2024", value = 0, category = "Godly", id = "floral_g_2024" },
    ["floral_k_2023"] = { name = "Floral K 2023", value = 0, category = "Godly", id = "floral_k_2023" },
    ["flowerwoodgun"] = { name = "Flowerwoodgun", value = 0, category = "Godly", id = "flowerwoodgun" },
    ["flowerwoodknife"] = { name = "Flowerwoodknife", value = 0, category = "Godly", id = "flowerwoodknife" },
    ["forest_g_2024"] = { name = "Forest G 2024", value = 0, category = "Common", id = "forest_g_2024" },
    ["fox"] = { name = "Fox", value = 0, category = "Pet", id = "fox" },
    ["foxchroma"] = { name = "Foxchroma", value = 0, category = "Chroma", id = "foxchroma" },
    ["foxfire"] = { name = "Foxfire", value = 0, category = "Pet", id = "foxfire" },
    ["Fragile_G_2023"] = { name = "Fragile G 2023", value = 0, category = "Common", id = "Fragile_G_2023" },
    ["Fragile_K_2023"] = { name = "Fragile K 2023", value = 0, category = "Common", id = "Fragile_K_2023" },
    ["frostbird"] = { name = "Frostbird", value = 1, category = "Godly", id = "frostbird" },
    ["frostbite"] = { name = "Frostbite", value = 7, category = "Godly", id = "frostbite" },
    ["frosted_g_2019"] = { name = "Frosted G 2019", value = 0, category = "Common", id = "frosted_g_2019" },
    ["frosted_k_2019"] = { name = "Frosted K 2019", value = 0, category = "Common", id = "frosted_k_2019" },
    ["frostfade_g_2023"] = { name = "Frostfade G 2023", value = 0, category = "Common", id = "frostfade_g_2023" },
    ["frostfade_k_2023"] = { name = "Frostfade K 2023", value = 0, category = "Common", id = "frostfade_k_2023" },
    ["frostflame_g_2024"] = { name = "Frostflame G 2024", value = 0, category = "Common", id = "frostflame_g_2024" },
    ["frostflame_k_2024"] = { name = "Frostflame K 2024", value = 0, category = "Common", id = "frostflame_k_2024" },
    ["frostsaber"] = { name = "Frostsaber", value = 10, category = "Godly", id = "frostsaber" },
    ["frosty"] = { name = "Frosty", value = 0, category = "Common", id = "frosty" },
    ["frozen_g_2019"] = { name = "Frozen G 2019", value = 0, category = "Common", id = "frozen_g_2019" },
    ["frozen_g_2023"] = { name = "Frozen G 2023", value = 0, category = "Common", id = "frozen_g_2023" },
    ["frozen_g_2025"] = { name = "Frozen G 2025", value = 0, category = "Common", id = "frozen_g_2025" },
    ["frozen_k_2019"] = { name = "Frozen K 2019", value = 0, category = "Common", id = "frozen_k_2019" },
    ["frozen_k_2023"] = { name = "Frozen K 2023", value = 0, category = "Common", id = "frozen_k_2023" },
    ["frozen_k_2025"] = { name = "Frozen K 2025", value = 0, category = "Common", id = "frozen_k_2025" },
    ["fusion"] = { name = "Fusion", value = 0, category = "Common", id = "fusion" },
    ["future"] = { name = "Future", value = 0, category = "Common", id = "future" },
    ["galactic"] = { name = "Galactic", value = 0, category = "Common", id = "galactic" },
    ["galaxy"] = { name = "Galaxy", value = 0, category = "Common", id = "galaxy" },
    ["gemstone"] = { name = "Gemstone", value = 17, category = "Godly", id = "gemstone" },
    ["gemstonechroma"] = { name = "Gemstonechroma", value = 0, category = "Godly", id = "gemstonechroma" },
    ["ghastly_g_2023"] = { name = "Ghastly G 2023", value = 0, category = "Common", id = "ghastly_g_2023" },
    ["ghastly_k_2023"] = { name = "Ghastly K 2023", value = 0, category = "Common", id = "ghastly_k_2023" },
    ["ghostblade"] = { name = "Ghostblade", value = 7, category = "Godly", id = "ghostblade" },
    ["ghostfire_g_2022"] = { name = "Ghostfire G 2022", value = 0, category = "Vintage", id = "ghostfire_g_2022" },
    ["ghostg2018"] = { name = "Ghostg2018", value = 0, category = "Vintage", id = "ghostg2018" },
    ["ghostk2018"] = { name = "Ghostk2018", value = 0, category = "Vintage", id = "ghostk2018" },
    ["ghostknife"] = { name = "Ghostknife", value = 0, category = "Vintage", id = "ghostknife" },
    ["ghostrbx_k_2022"] = { name = "Ghostrbx K 2022", value = 0, category = "Vintage", id = "ghostrbx_k_2022" },
    ["ghosts_g_2020"] = { name = "Ghosts G 2020", value = 0, category = "Vintage", id = "ghosts_g_2020" },
    ["ghosts_g_2021"] = { name = "Ghosts G 2021", value = 0, category = "Vintage", id = "ghosts_g_2021" },
    ["ghosts_k_2020"] = { name = "Ghosts K 2020", value = 0, category = "Vintage", id = "ghosts_k_2020" },
    ["ghosts_k_2021"] = { name = "Ghosts K 2021", value = 0, category = "Vintage", id = "ghosts_k_2021" },
    ["ghosts_k_2023"] = { name = "Ghosts K 2023", value = 0, category = "Vintage", id = "ghosts_k_2023" },
    ["ghosts_k_2024"] = { name = "Ghosts K 2024", value = 0, category = "Vintage", id = "ghosts_k_2024" },
    ["ghosty"] = { name = "Ghosty", value = 1, category = "Vintage", id = "ghosty" },
    ["gift"] = { name = "Gift", value = 0, category = "Common", id = "gift" },
    ["gift_g_2020"] = { name = "Gift G 2020", value = 0, category = "Common", id = "gift_g_2020" },
    ["gift_k_2020"] = { name = "Gift K 2020", value = 0, category = "Common", id = "gift_k_2020" },
    ["giftbag_g_2020"] = { name = "Giftbag G 2020", value = 0, category = "Common", id = "giftbag_g_2020" },
    ["giftbag_k_2020"] = { name = "Giftbag K 2020", value = 0, category = "Common", id = "giftbag_k_2020" },
    ["gifted"] = { name = "Gifted", value = 0, category = "Common", id = "gifted" },
    ["gifts_g_2019"] = { name = "Gifts G 2019", value = 0, category = "Common", id = "gifts_g_2019" },
    ["gifts_k_2019"] = { name = "Gifts K 2019", value = 0, category = "Common", id = "gifts_k_2019" },
    ["gifts_k_2024"] = { name = "Gifts K 2024", value = 0, category = "Common", id = "gifts_k_2024" },
    ["giftwrap_k_2021"] = { name = "Giftwrap K 2021", value = 0, category = "Common", id = "giftwrap_k_2021" },
    ["ginger"] = { name = "Ginger", value = 0, category = "Common", id = "ginger" },
    ["ginger_g_2018"] = { name = "Ginger G 2018", value = 0, category = "Common", id = "ginger_g_2018" },
    ["ginger_k_2018"] = { name = "Ginger K 2018", value = 0, category = "Common", id = "ginger_k_2018" },
    ["gingerblade"] = { name = "Gingerblade", value = 0, category = "Knife", id = "gingerblade" },
    ["gingerbladechroma"] = { name = "Gingerbladechroma", value = 0, category = "Chroma", id = "gingerbladechroma" },
    ["gingerbread_g_2019"] = { name = "Gingerbread G 2019", value = 0, category = "Common", id = "gingerbread_g_2019" },
    ["gingerbread_g_2020"] = { name = "Gingerbread G 2020", value = 0, category = "Common", id = "gingerbread_g_2020" },
    ["gingerbread_g_2021"] = { name = "Gingerbread G 2021", value = 0, category = "Common", id = "gingerbread_g_2021" },
    ["gingerbread_g_2022"] = { name = "Gingerbread G 2022", value = 0, category = "Common", id = "gingerbread_g_2022" },
    ["gingerbread_g_2025"] = { name = "Gingerbread G 2025", value = 0, category = "Common", id = "gingerbread_g_2025" },
    ["gingerbread_k_2019"] = { name = "Gingerbread K 2019", value = 0, category = "Common", id = "gingerbread_k_2019" },
    ["gingerbread_k_2020"] = { name = "Gingerbread K 2020", value = 0, category = "Common", id = "gingerbread_k_2020" },
    ["gingerbread_k_2022"] = { name = "Gingerbread K 2022", value = 0, category = "Common", id = "gingerbread_k_2022" },
    ["gingerbread_k_2025"] = { name = "Gingerbread K 2025", value = 0, category = "Common", id = "gingerbread_k_2025" },
    ["gingerbread2017"] = { name = "Gingerbread2017", value = 0, category = "Common", id = "gingerbread2017" },
    ["gingercookie_g_2025"] = { name = "Gingercookie G 2025", value = 0, category = "Common", id = "gingercookie_g_2025" },
    ["gingercookie_k_2025"] = { name = "Gingercookie K 2025", value = 0, category = "Common", id = "gingercookie_k_2025" },
    ["gingergun"] = { name = "Gingergun", value = 0, category = "Gun", id = "gingergun" },
    ["gingerheart_k_2024"] = { name = "Gingerheart K 2024", value = 0, category = "Common", id = "gingerheart_k_2024" },
    ["gingerluger"] = { name = "Gingerluger", value = 0, category = "Godly", id = "gingerluger" },
    ["gingermint_g"] = { name = "Gingermint G", value = 0, category = "Common", id = "gingermint_g" },
    ["gingermint_k"] = { name = "Gingermint K", value = 0, category = "Common", id = "gingermint_k" },
    ["gingermint_kchroma"] = { name = "Gingermint Kchroma", value = 0, category = "Chroma", id = "gingermint_kchroma" },
    ["gingerscope"] = { name = "Gingerscope", value = 14000, category = "Ancient", id = "gingerscope" },
    ["glowy_k_2023"] = { name = "Glowy K 2023", value = 0, category = "Common", id = "glowy_k_2023" },
    ["goldengun"] = { name = "Goldengun", value = 0, category = "Gun", id = "goldengun" },
    ["goo"] = { name = "Goo", value = 0, category = "Common", id = "goo" },
    ["gothic_g_2021"] = { name = "Gothic G 2021", value = 0, category = "Common", id = "gothic_g_2021" },
    ["gothic_k_2021"] = { name = "Gothic K 2021", value = 0, category = "Common", id = "gothic_k_2021" },
    ["graffiti"] = { name = "Graffiti", value = 0, category = "Common", id = "graffiti" },
    ["graveg"] = { name = "Graveg", value = 0, category = "Common", id = "graveg" },
    ["gravek"] = { name = "Gravek", value = 0, category = "Common", id = "gravek" },
    ["greencamo_k_2022"] = { name = "Greencamo K 2022", value = 0, category = "Common", id = "greencamo_k_2022" },
    ["greenfire"] = { name = "Greenfire", value = 0, category = "Common", id = "greenfire" },
    ["greenluger"] = { name = "Greenluger", value = 0, category = "Godly", id = "greenluger" },
    ["greenmarble"] = { name = "Greenmarble", value = 0, category = "Common", id = "greenmarble" },
    ["greenp"] = { name = "Greenp", value = 0, category = "Common", id = "greenp" },
    ["greenpumpkin19"] = { name = "Greenpumpkin19", value = 0, category = "Common", id = "greenpumpkin19" },
    ["greenpumpkin2020"] = { name = "Greenpumpkin2020", value = 0, category = "Common", id = "greenpumpkin2020" },
    ["greenpumpkin2021"] = { name = "Greenpumpkin2021", value = 0, category = "Common", id = "greenpumpkin2021" },
    ["grind"] = { name = "Grind", value = 0, category = "Common", id = "grind" },
    ["gun1"] = { name = "Gun1", value = 0, category = "Gun", id = "gun1" },
    ["hacker"] = { name = "Hacker", value = 0, category = "Common", id = "hacker" },
    ["hallow"] = { name = "Hallow", value = 0, category = "Godly", id = "hallow" },
    ["hallowgun"] = { name = "Hallowgun", value = 45, category = "Ancient", id = "hallowgun" },
    ["hallowsblade"] = { name = "Hallowsblade", value = 0, category = "Godly", id = "hallowsblade" },
    ["hallowscythe"] = { name = "Hallowscythe", value = 0, category = "Godly", id = "hallowscythe" },
    ["handsaw"] = { name = "Handsaw", value = 8, category = "Godly", id = "handsaw" },
    ["hardened"] = { name = "Hardened", value = 0, category = "Common", id = "hardened" },
    ["harvester"] = { name = "Harvester", value = 425, category = "Ancient", id = "harvester" },
    ["hauntedg"] = { name = "Hauntedg", value = 0, category = "Common", id = "hauntedg" },
    ["hauntedhouse_k_2025"] = { name = "Hauntedhouse K 2025", value = 0, category = "Common", id = "hauntedhouse_k_2025" },
    ["hauntedk"] = { name = "Hauntedk", value = 0, category = "Common", id = "hauntedk" },
    ["hazard_g_2022"] = { name = "Hazard G 2022", value = 0, category = "Common", id = "hazard_g_2022" },
    ["hazard_k_2022"] = { name = "Hazard K 2022", value = 0, category = "Common", id = "hazard_k_2022" },
    ["hazmat"] = { name = "Hazmat", value = 0, category = "Common", id = "hazmat" },
    ["heart_k_2023"] = { name = "Heart K 2023", value = 0, category = "Common", id = "heart_k_2023" },
    ["heartblade"] = { name = "Heartblade", value = 0, category = "Knife", id = "heartblade" },
    ["hearts"] = { name = "Hearts", value = 0, category = "Common", id = "hearts" },
    ["HeartWand"] = { name = "HeartWand", value = 0, category = "Common", id = "HeartWand" },
    ["heat"] = { name = "Heat", value = 10, category = "Godly", id = "heat" },
    ["heatchroma"] = { name = "Heatchroma", value = 0, category = "Godly", id = "heatchroma" },
    ["hightech"] = { name = "Hightech", value = 0, category = "Common", id = "hightech" },
    ["hive"] = { name = "Hive", value = 0, category = "Common", id = "hive" },
    ["hl2"] = { name = "Hl2", value = 0, category = "Common", id = "hl2" },
    ["holly_g_2018"] = { name = "Holly G 2018", value = 0, category = "Common", id = "holly_g_2018" },
    ["holly_k_2018"] = { name = "Holly K 2018", value = 0, category = "Common", id = "holly_k_2018" },
    ["hologram_g_2025"] = { name = "Hologram G 2025", value = 0, category = "Common", id = "hologram_g_2025" },
    ["hologram_k_2025"] = { name = "Hologram K 2025", value = 0, category = "Common", id = "hologram_k_2025" },
    ["hotchocolate_k_2024"] = { name = "Hotchocolate K 2024", value = 0, category = "Common", id = "hotchocolate_k_2024" },
    ["hunter_k_2022"] = { name = "Hunter K 2022", value = 0, category = "Common", id = "hunter_k_2022" },
    ["ice"] = { name = "Ice", value = 0, category = "Common", id = "ice" },
    ["icebeam"] = { name = "Icebeam", value = 60, category = "Godly", id = "icebeam" },
    ["iceblaster"] = { name = "Iceblaster", value = 0, category = "Godly", id = "iceblaster" },
    ["icebreaker"] = { name = "Icebreaker", value = 115, category = "Ancient", id = "icebreaker" },
    ["icecamo_g_2021"] = { name = "Icecamo G 2021", value = 0, category = "Common", id = "icecamo_g_2021" },
    ["icecracker_k_2020"] = { name = "Icecracker K 2020", value = 0, category = "Common", id = "icecracker_k_2020" },
    ["icedragon"] = { name = "Icedragon", value = 0, category = "Godly", id = "icedragon" },
    ["icedriller_g_2020"] = { name = "Icedriller G 2020", value = 0, category = "Common", id = "icedriller_g_2020" },
    ["iceflake"] = { name = "Iceflake", value = 25, category = "Godly", id = "iceflake" },
    ["icephoenix"] = { name = "Icephoenix", value = 0, category = "Godly", id = "icephoenix" },
    ["icepiercer"] = { name = "Icepiercer", value = 350, category = "Ancient", id = "icepiercer" },
    ["iceshard"] = { name = "Iceshard", value = 0, category = "Godly", id = "iceshard" },
    ["icewing"] = { name = "Icewing", value = 12, category = "Ancient", id = "icewing" },
    ["icey"] = { name = "Icey", value = 0, category = "Common", id = "icey" },
    ["icicles_g_2018"] = { name = "Icicles G 2018", value = 0, category = "Common", id = "icicles_g_2018" },
    ["icicles_k_2018"] = { name = "Icicles K 2018", value = 0, category = "Common", id = "icicles_k_2018" },
    ["igloo_g_2024"] = { name = "Igloo G 2024", value = 0, category = "Common", id = "igloo_g_2024" },
    ["igloo_k_2024"] = { name = "Igloo K 2024", value = 0, category = "Common", id = "igloo_k_2024" },
    ["imbued"] = { name = "Imbued", value = 0, category = "Common", id = "imbued" },
    ["indy"] = { name = "Indy", value = 0, category = "Common", id = "indy" },
    ["infected"] = { name = "Infected", value = 0, category = "Common", id = "infected" },
    ["infected_g_2022"] = { name = "Infected G 2022", value = 0, category = "Common", id = "infected_g_2022" },
    ["infected_k_2022"] = { name = "Infected K 2022", value = 0, category = "Common", id = "infected_k_2022" },
    ["infiltrator"] = { name = "Infiltrator", value = 0, category = "Common", id = "infiltrator" },
    ["irevolver"] = { name = "Irevolver", value = 0, category = "Gun", id = "irevolver" },
    ["iron"] = { name = "Iron", value = 0, category = "Common", id = "iron" },
    ["jack"] = { name = "Jack", value = 0, category = "Common", id = "jack" },
    ["jack_k_2022"] = { name = "Jack K 2022", value = 0, category = "Common", id = "jack_k_2022" },
    ["jd"] = { name = "Jd", value = 0, category = "Common", id = "jd" },
    ["jellyfish_k_2024"] = { name = "Jellyfish K 2024", value = 0, category = "Common", id = "jellyfish_k_2024" },
    ["jetstream"] = { name = "Jetstream", value = 0, category = "Common", id = "jetstream" },
    ["jigsaw"] = { name = "Jigsaw", value = 0, category = "Godly", id = "jigsaw" },
    ["jinglegun"] = { name = "Jinglegun", value = 17, category = "Godly", id = "jinglegun" },
    ["Key"] = { name = "Key", value = 0, category = "Common", id = "Key" },
    ["knife1"] = { name = "Knife1", value = 0, category = "Vintage", id = "knife1" },
    ["kool"] = { name = "Kool", value = 0, category = "Common", id = "kool" },
    ["korblox"] = { name = "Korblox", value = 0, category = "Common", id = "korblox" },
    ["kraken_k_2024"] = { name = "Kraken K 2024", value = 0, category = "Common", id = "kraken_k_2024" },
    ["krypto"] = { name = "Krypto", value = 0, category = "Common", id = "krypto" },
    ["laser"] = { name = "Laser", value = 27, category = "Godly", id = "laser" },
    ["laserchroma"] = { name = "Laserchroma", value = 0, category = "Godly", id = "laserchroma" },
    ["latte_g_2023"] = { name = "Latte G 2023", value = 0, category = "Common", id = "latte_g_2023" },
    ["latte_k_2023"] = { name = "Latte K 2023", value = 0, category = "Common", id = "latte_k_2023" },
    ["lava_g_2025"] = { name = "Lava G 2025", value = 0, category = "Common", id = "lava_g_2025" },
    ["lava_k_2025"] = { name = "Lava K 2025", value = 0, category = "Common", id = "lava_k_2025" },
    ["leaf"] = { name = "Leaf", value = 0, category = "Common", id = "leaf" },
    ["leaves_g_2024"] = { name = "Leaves G 2024", value = 0, category = "Common", id = "leaves_g_2024" },
    ["leaves_k_2023"] = { name = "Leaves K 2023", value = 0, category = "Common", id = "leaves_k_2023" },
    ["leaves_k_2025"] = { name = "Leaves K 2025", value = 0, category = "Common", id = "leaves_k_2025" },
    ["lightbringer"] = { name = "Lightbringer", value = 50, category = "Godly", id = "lightbringer" },
    ["lights_g_2019"] = { name = "Lights G 2019", value = 0, category = "Common", id = "lights_g_2019" },
    ["lights_g_2025"] = { name = "Lights G 2025", value = 0, category = "Common", id = "lights_g_2025" },
    ["lights_k_2019"] = { name = "Lights K 2019", value = 0, category = "Common", id = "lights_k_2019" },
    ["lights_k_2025"] = { name = "Lights K 2025", value = 0, category = "Common", id = "lights_k_2025" },
    ["linked"] = { name = "Linked", value = 0, category = "Common", id = "linked" },
    ["lmfao"] = { name = "Lmfao", value = 0, category = "Common", id = "lmfao" },
    ["log"] = { name = "Log", value = 0, category = "Common", id = "log" },
    ["logchopper"] = { name = "Logchopper", value = 20, category = "Ancient", id = "logchopper" },
    ["logcutter_k_2024"] = { name = "Logcutter K 2024", value = 0, category = "Common", id = "logcutter_k_2024" },
    ["love"] = { name = "Love", value = 0, category = "Common", id = "love" },
    ["Love_K_2023"] = { name = "Love K 2023", value = 0, category = "Common", id = "Love_K_2023" },
    ["lovegun"] = { name = "Lovegun", value = 0, category = "Gun", id = "lovegun" },
    ["lovely"] = { name = "Lovely", value = 0, category = "Common", id = "lovely" },
    ["lucky"] = { name = "Lucky", value = 0, category = "Common", id = "lucky" },
    ["luger"] = { name = "Luger", value = 60, category = "Godly", id = "luger" },
    ["lugercane"] = { name = "Lugercane", value = 18, category = "Godly", id = "lugercane" },
    ["lugerchroma"] = { name = "Lugerchroma", value = 0, category = "Godly", id = "lugerchroma" },
    ["magma_g_2021"] = { name = "Magma G 2021", value = 0, category = "Common", id = "magma_g_2021" },
    ["magma_k_2021"] = { name = "Magma K 2021", value = 0, category = "Common", id = "magma_k_2021" },
    ["magmak"] = { name = "Magmak", value = 0, category = "Common", id = "magmak" },
    ["makeshift"] = { name = "Makeshift", value = 0, category = "Common", id = "makeshift" },
    ["Marble_K_2023"] = { name = "Marble K 2023", value = 0, category = "Common", id = "Marble_K_2023" },
    ["marina"] = { name = "Marina", value = 0, category = "Common", id = "marina" },
    ["marley"] = { name = "Marley", value = 0, category = "Common", id = "marley" },
    ["meadow_g_2025"] = { name = "Meadow G 2025", value = 0, category = "Common", id = "meadow_g_2025" },
    ["mechbug"] = { name = "Mechbug", value = 0, category = "Common", id = "mechbug" },
    ["melon"] = { name = "Melon", value = 0, category = "Common", id = "melon" },
    ["melon_g_2023"] = { name = "Melon G 2023", value = 0, category = "Common", id = "melon_g_2023" },
    ["meltdown_k_2023"] = { name = "Meltdown K 2023", value = 0, category = "Common", id = "meltdown_k_2023" },
    ["midnight"] = { name = "Midnight", value = 0, category = "Common", id = "midnight" },
    ["minty"] = { name = "Minty", value = 0, category = "Common", id = "minty" },
    ["missing"] = { name = "Missing", value = 0, category = "Common", id = "missing" },
    ["mistletoe_g_2022"] = { name = "Mistletoe G 2022", value = 0, category = "Common", id = "mistletoe_g_2022" },
    ["mistletoe_k_2022"] = { name = "Mistletoe K 2022", value = 0, category = "Common", id = "mistletoe_k_2022" },
    ["mlg"] = { name = "Mlg", value = 0, category = "Common", id = "mlg" },
    ["molten"] = { name = "Molten", value = 0, category = "Common", id = "molten" },
    ["moltenknife"] = { name = "Moltenknife", value = 0, category = "Knife", id = "moltenknife" },
    ["monster"] = { name = "Monster", value = 0, category = "Common", id = "monster" },
    ["monster_k_2024"] = { name = "Monster K 2024", value = 0, category = "Common", id = "monster_k_2024" },
    ["moon_k_2021"] = { name = "Moon K 2021", value = 0, category = "Common", id = "moon_k_2021" },
    ["moonlight_g_2022"] = { name = "Moonlight G 2022", value = 0, category = "Common", id = "moonlight_g_2022" },
    ["moons"] = { name = "Moons", value = 0, category = "Common", id = "moons" },
    ["moons_k_2024"] = { name = "Moons K 2024", value = 0, category = "Common", id = "moons_k_2024" },
    ["mummified"] = { name = "Mummified", value = 0, category = "Common", id = "mummified" },
    ["mummy"] = { name = "Mummy", value = 0, category = "Common", id = "mummy" },
    ["mummy_g_2020"] = { name = "Mummy G 2020", value = 0, category = "Common", id = "mummy_g_2020" },
    ["mummy_k_2020"] = { name = "Mummy K 2020", value = 0, category = "Common", id = "mummy_k_2020" },
    ["mummyg2018"] = { name = "Mummyg2018", value = 0, category = "Common", id = "mummyg2018" },
    ["mummyk"] = { name = "Mummyk", value = 0, category = "Common", id = "mummyk" },
    ["mummyk2018"] = { name = "Mummyk2018", value = 0, category = "Common", id = "mummyk2018" },
    ["musical"] = { name = "Musical", value = 0, category = "Common", id = "musical" },
    ["nebula"] = { name = "Nebula", value = 0, category = "Common", id = "nebula" },
    ["neon"] = { name = "Neon", value = 0, category = "Common", id = "neon" },
    ["neon_g_2023"] = { name = "Neon G 2023", value = 0, category = "Common", id = "neon_g_2023" },
    ["neon_g_2025"] = { name = "Neon G 2025", value = 0, category = "Common", id = "neon_g_2025" },
    ["nether"] = { name = "Nether", value = 0, category = "Common", id = "nether" },
    ["news"] = { name = "News", value = 0, category = "Common", id = "news" },
    ["night"] = { name = "Night", value = 0, category = "Common", id = "night" },
    ["nightblade"] = { name = "Nightblade", value = 22, category = "Godly", id = "nightblade" },
    ["nightfire"] = { name = "Nightfire", value = 0, category = "Common", id = "nightfire" },
    ["nobledragon"] = { name = "Nobledragon", value = 0, category = "Common", id = "nobledragon" },
    ["noodle_k_2023"] = { name = "Noodle K 2023", value = 0, category = "Common", id = "noodle_k_2023" },
    ["nova"] = { name = "Nova", value = 0, category = "Common", id = "nova" },
    ["nuke_g_2023"] = { name = "Nuke G 2023", value = 0, category = "Common", id = "nuke_g_2023" },
    ["nutcracker"] = { name = "Nutcracker", value = 0, category = "Common", id = "nutcracker" },
    ["ocean_g"] = { name = "Ocean G", value = 0, category = "Common", id = "ocean_g" },
    ["oily"] = { name = "Oily", value = 0, category = "Common", id = "oily" },
    ["ollie"] = { name = "Ollie", value = 0, category = "Common", id = "ollie" },
    ["orangemarble"] = { name = "Orangemarble", value = 0, category = "Common", id = "orangemarble" },
    ["orangeseer"] = { name = "Orangeseer", value = 0, category = "Godly", id = "orangeseer" },
    ["ornament1"] = { name = "Ornament1", value = 0, category = "Common", id = "ornament1" },
    ["ornament1gun"] = { name = "Ornament1gun", value = 0, category = "Gun", id = "ornament1gun" },
    ["ornament2"] = { name = "Ornament2", value = 0, category = "Common", id = "ornament2" },
    ["ornament2gun"] = { name = "Ornament2gun", value = 0, category = "Gun", id = "ornament2gun" },
    ["ornaments_g_2020"] = { name = "Ornaments G 2020", value = 0, category = "Common", id = "ornaments_g_2020" },
    ["ornaments_k_2020"] = { name = "Ornaments K 2020", value = 0, category = "Common", id = "ornaments_k_2020" },
    ["ornaments_k_2025"] = { name = "Ornaments K 2025", value = 0, category = "Common", id = "ornaments_k_2025" },
    ["overseer"] = { name = "Overseer", value = 0, category = "Godly", id = "overseer" },
    ["overseer_eye"] = { name = "Overseer Eye", value = 0, category = "Godly", id = "overseer_eye" },
    ["overseerknife"] = { name = "Overseerknife", value = 0, category = "Godly", id = "overseerknife" },
    ["Painted_G_2023"] = { name = "Painted G 2023", value = 0, category = "Common", id = "Painted_G_2023" },
    ["painted_k_2023"] = { name = "Painted K 2023", value = 0, category = "Common", id = "painted_k_2023" },
    ["palms_g_2024"] = { name = "Palms G 2024", value = 0, category = "Common", id = "palms_g_2024" },
    ["palms_k_2024"] = { name = "Palms K 2024", value = 0, category = "Common", id = "palms_k_2024" },
    ["paper"] = { name = "Paper", value = 0, category = "Common", id = "paper" },
    ["passion"] = { name = "Passion", value = 0, category = "Common", id = "passion" },
    ["patrick"] = { name = "Patrick", value = 0, category = "Common", id = "patrick" },
    ["pea"] = { name = "Pea", value = 0, category = "Common", id = "pea" },
    ["pearl_g"] = { name = "Pearl G", value = 0, category = "Common", id = "pearl_g" },
    ["pearl_k"] = { name = "Pearl K", value = 0, category = "Common", id = "pearl_k" },
    ["penguin_k_2025"] = { name = "Penguin K 2025", value = 0, category = "Common", id = "penguin_k_2025" },
    ["pengy"] = { name = "Pengy", value = 0, category = "Pet", id = "pengy" },
    ["pepper"] = { name = "Pepper", value = 0, category = "Common", id = "pepper" },
    ["peppermint"] = { name = "Peppermint", value = 4, category = "Godly", id = "peppermint" },
    ["peppermint_k_2025"] = { name = "Peppermint K 2025", value = 0, category = "Godly", id = "peppermint_k_2025" },
    ["phantom"] = { name = "Phantom", value = 0, category = "Common", id = "phantom" },
    ["phantom2022"] = { name = "Phantom2022", value = 0, category = "Common", id = "phantom2022" },
    ["phaser"] = { name = "Phaser", value = 5, category = "Vintage", id = "phaser" },
    ["phoenix"] = { name = "Phoenix", value = 1, category = "Godly", id = "phoenix" },
    ["pig"] = { name = "Pig", value = 0, category = "Pet", id = "pig" },
    ["pigchroma"] = { name = "Pigchroma", value = 0, category = "Chroma", id = "pigchroma" },
    ["pigfire"] = { name = "Pigfire", value = 0, category = "Pet", id = "pigfire" },
    ["piggy"] = { name = "Piggy", value = 0, category = "Pet", id = "piggy" },
    ["pine_g_2019"] = { name = "Pine G 2019", value = 0, category = "Common", id = "pine_g_2019" },
    ["pine_k_2019"] = { name = "Pine K 2019", value = 0, category = "Common", id = "pine_k_2019" },
    ["pirate"] = { name = "Pirate", value = 0, category = "Common", id = "pirate" },
    ["pixel"] = { name = "Pixel", value = 25, category = "Godly", id = "pixel" },
    ["plasmabeam"] = { name = "Plasmabeam", value = 0, category = "Gun", id = "plasmabeam" },
    ["plasmablade"] = { name = "Plasmablade", value = 0, category = "Knife", id = "plasmablade" },
    ["plasmite"] = { name = "Plasmite", value = 0, category = "Common", id = "plasmite" },
    ["polarbear_k_2025"] = { name = "Polarbear K 2025", value = 0, category = "Pet", id = "polarbear_k_2025" },
    ["pool_k_2025"] = { name = "Pool K 2025", value = 0, category = "Common", id = "pool_k_2025" },
    ["popart_g_2025"] = { name = "Popart G 2025", value = 0, category = "Common", id = "popart_g_2025" },
    ["popart_k_2025"] = { name = "Popart K 2025", value = 0, category = "Common", id = "popart_k_2025" },
    ["popsicle_g_2024"] = { name = "Popsicle G 2024", value = 0, category = "Common", id = "popsicle_g_2024" },
    ["popsicle_k_2023"] = { name = "Popsicle K 2023", value = 0, category = "Common", id = "popsicle_k_2023" },
    ["portal_g_2020"] = { name = "Portal G 2020", value = 0, category = "Common", id = "portal_g_2020" },
    ["portal_k_2020"] = { name = "Portal K 2020", value = 0, category = "Common", id = "portal_k_2020" },
    ["potion"] = { name = "Potion", value = 0, category = "Common", id = "potion" },
    ["potiong2018"] = { name = "Potiong2018", value = 0, category = "Common", id = "potiong2018" },
    ["potionk2018"] = { name = "Potionk2018", value = 0, category = "Common", id = "potionk2018" },
    ["predator"] = { name = "Predator", value = 0, category = "Common", id = "predator" },
    ["predatorknife"] = { name = "Predatorknife", value = 0, category = "Knife", id = "predatorknife" },
    ["present"] = { name = "Present", value = 0, category = "Common", id = "present" },
    ["present_k_2023"] = { name = "Present K 2023", value = 0, category = "Common", id = "present_k_2023" },
    ["prism"] = { name = "Prism", value = 0, category = "Common", id = "prism" },
    ["prismatic"] = { name = "Prismatic", value = 7, category = "Godly", id = "prismatic" },
    ["pumpkin_g_2023"] = { name = "Pumpkin G 2023", value = 0, category = "Common", id = "pumpkin_g_2023" },
    ["pumpkin2020"] = { name = "Pumpkin2020", value = 0, category = "Common", id = "pumpkin2020" },
    ["pumpkin2021"] = { name = "Pumpkin2021", value = 0, category = "Common", id = "pumpkin2021" },
    ["pumpking"] = { name = "Pumpking", value = 7, category = "Godly", id = "pumpking" },
    ["pumpkinpatch"] = { name = "Pumpkinpatch", value = 0, category = "Common", id = "pumpkinpatch" },
    ["pumpkinpatch_g_2025"] = { name = "Pumpkinpatch G 2025", value = 0, category = "Common", id = "pumpkinpatch_g_2025" },
    ["pumpkinpatch_k_2025"] = { name = "Pumpkinpatch K 2025", value = 0, category = "Common", id = "pumpkinpatch_k_2025" },
    ["pumpkinpet"] = { name = "Pumpkinpet", value = 0, category = "Pet", id = "pumpkinpet" },
    ["pumpkinpet18"] = { name = "Pumpkinpet18", value = 0, category = "Pet", id = "pumpkinpet18" },
    ["pumpkinpet19"] = { name = "Pumpkinpet19", value = 0, category = "Pet", id = "pumpkinpet19" },
    ["pumpkinpie_k_2023"] = { name = "Pumpkinpie K 2023", value = 0, category = "Common", id = "pumpkinpie_k_2023" },
    ["purplep"] = { name = "Purplep", value = 0, category = "Common", id = "purplep" },
    ["purpleseer"] = { name = "Purpleseer", value = 0, category = "Godly", id = "purpleseer" },
    ["rainbow"] = { name = "Rainbow", value = 0, category = "Common", id = "rainbow" },
    ["rainbow_g"] = { name = "Rainbow G", value = 0, category = "Common", id = "rainbow_g" },
    ["rainbow_k"] = { name = "Rainbow K", value = 0, category = "Common", id = "rainbow_k" },
    ["rainbowgun"] = { name = "Rainbowgun", value = 0, category = "Gun", id = "rainbowgun" },
    ["randluger"] = { name = "Randluger", value = 0, category = "Godly", id = "randluger" },
    ["raygun"] = { name = "Raygun", value = 475, category = "Godly", id = "raygun" },
    ["raygunchroma"] = { name = "Raygunchroma", value = 0, category = "Godly", id = "raygunchroma" },
    ["rbknife"] = { name = "Rbknife", value = 0, category = "Knife", id = "rbknife" },
    ["rbxscary_k_2023"] = { name = "Rbxscary K 2023", value = 0, category = "Common", id = "rbxscary_k_2023" },
    ["redfire"] = { name = "Redfire", value = 0, category = "Common", id = "redfire" },
    ["redluger"] = { name = "Redluger", value = 0, category = "Godly", id = "redluger" },
    ["redp"] = { name = "Redp", value = 0, category = "Common", id = "redp" },
    ["redpumpkin19"] = { name = "Redpumpkin19", value = 0, category = "Common", id = "redpumpkin19" },
    ["redpumpkin2020"] = { name = "Redpumpkin2020", value = 0, category = "Common", id = "redpumpkin2020" },
    ["redpumpkin2021"] = { name = "Redpumpkin2021", value = 0, category = "Common", id = "redpumpkin2021" },
    ["redseer"] = { name = "Redseer", value = 0, category = "Godly", id = "redseer" },
    ["reindeer"] = { name = "Reindeer", value = 0, category = "Pet", id = "reindeer" },
    ["reindeer_k_2025"] = { name = "Reindeer K 2025", value = 0, category = "Pet", id = "reindeer_k_2025" },
    ["reindeer2020"] = { name = "Reindeer2020", value = 0, category = "Pet", id = "reindeer2020" },
    ["reptile"] = { name = "Reptile", value = 0, category = "Common", id = "reptile" },
    ["retro_k_2025"] = { name = "Retro K 2025", value = 0, category = "Common", id = "retro_k_2025" },
    ["ribbon_k_2023"] = { name = "Ribbon K 2023", value = 0, category = "Common", id = "ribbon_k_2023" },
    ["ribbons_k_2021"] = { name = "Ribbons K 2021", value = 0, category = "Common", id = "ribbons_k_2021" },
    ["rip"] = { name = "Rip", value = 0, category = "Common", id = "rip" },
    ["ripper_g_2020"] = { name = "Ripper G 2020", value = 0, category = "Common", id = "ripper_g_2020" },
    ["ripper_k_2020"] = { name = "Ripper K 2020", value = 0, category = "Common", id = "ripper_k_2020" },
    ["ritual_g_2024"] = { name = "Ritual G 2024", value = 0, category = "Common", id = "ritual_g_2024" },
    ["robot_k_2024"] = { name = "Robot K 2024", value = 0, category = "Common", id = "robot_k_2024" },
    ["Rose_K_2023"] = { name = "Rose K 2023", value = 0, category = "Common", id = "Rose_K_2023" },
    ["roses"] = { name = "Roses", value = 0, category = "Common", id = "roses" },
    ["rudolph"] = { name = "Rudolph", value = 0, category = "Common", id = "rudolph" },
    ["rune"] = { name = "Rune", value = 0, category = "Common", id = "rune" },
    ["runic_k_2022"] = { name = "Runic K 2022", value = 0, category = "Common", id = "runic_k_2022" },
    ["sakura_k"] = { name = "Sakura K", value = 0, category = "Common", id = "sakura_k" },
    ["sandy"] = { name = "Sandy", value = 0, category = "Common", id = "sandy" },
    ["sandy_g_2024"] = { name = "Sandy G 2024", value = 0, category = "Common", id = "sandy_g_2024" },
    ["santa"] = { name = "Santa", value = 0, category = "Common", id = "santa" },
    ["santa_g_2018"] = { name = "Santa G 2018", value = 0, category = "Common", id = "santa_g_2018" },
    ["santa_g_2023"] = { name = "Santa G 2023", value = 0, category = "Common", id = "santa_g_2023" },
    ["santa_k_2018"] = { name = "Santa K 2018", value = 0, category = "Common", id = "santa_k_2018" },
    ["santa2017"] = { name = "Santa2017", value = 0, category = "Common", id = "santa2017" },
    ["santadog"] = { name = "Santadog", value = 0, category = "Pet", id = "santadog" },
    ["santagun"] = { name = "Santagun", value = 0, category = "Gun", id = "santagun" },
    ["santasmagic"] = { name = "Santasmagic", value = 0, category = "Common", id = "santasmagic" },
    ["santasspirit"] = { name = "Santasspirit", value = 0, category = "Common", id = "santasspirit" },
    ["saw"] = { name = "Saw", value = 7, category = "Godly", id = "saw" },
    ["sawchroma"] = { name = "Sawchroma", value = 0, category = "Godly", id = "sawchroma" },
    ["scarecrow2020"] = { name = "Scarecrow2020", value = 0, category = "Common", id = "scarecrow2020" },
    ["scarf_k_2023"] = { name = "Scarf K 2023", value = 0, category = "Common", id = "scarf_k_2023" },
    ["scratch"] = { name = "Scratch", value = 0, category = "Common", id = "scratch" },
    ["scratchblue"] = { name = "Scratchblue", value = 0, category = "Common", id = "scratchblue" },
    ["scythe"] = { name = "Scythe", value = 0, category = "Knife", id = "scythe" },
    ["seahorsey"] = { name = "Seahorsey", value = 0, category = "Common", id = "seahorsey" },
    ["seerchroma"] = { name = "Seerchroma", value = 0, category = "Godly", id = "seerchroma" },
    ["shaded"] = { name = "Shaded", value = 0, category = "Common", id = "shaded" },
    ["shadowknife"] = { name = "Shadowknife", value = 0, category = "Vintage", id = "shadowknife" },
    ["shadowpumpkin2021"] = { name = "Shadowpumpkin2021", value = 0, category = "Vintage", id = "shadowpumpkin2021" },
    ["shark"] = { name = "Shark", value = 23, category = "Godly", id = "shark" },
    ["sharkchroma"] = { name = "Sharkchroma", value = 0, category = "Godly", id = "sharkchroma" },
    ["sharky_k_2024"] = { name = "Sharky K 2024", value = 0, category = "Godly", id = "sharky_k_2024" },
    ["sidewinder"] = { name = "Sidewinder", value = 0, category = "Common", id = "sidewinder" },
    ["silentnight_g_2020"] = { name = "Silentnight G 2020", value = 0, category = "Common", id = "silentnight_g_2020" },
    ["silentnight_k_2020"] = { name = "Silentnight K 2020", value = 0, category = "Common", id = "silentnight_k_2020" },
    ["skeletonkey"] = { name = "Skeletonkey", value = 0, category = "Common", id = "skeletonkey" },
    ["skelly"] = { name = "Skelly", value = 1, category = "Godly", id = "skelly" },
    ["sketch"] = { name = "Sketch", value = 0, category = "Common", id = "sketch" },
    ["sketchyt"] = { name = "Sketchyt", value = 0, category = "Common", id = "sketchyt" },
    ["skool"] = { name = "Skool", value = 0, category = "Common", id = "skool" },
    ["skull_k_2023"] = { name = "Skull K 2023", value = 0, category = "Common", id = "skull_k_2023" },
    ["skull2021"] = { name = "Skull2021", value = 0, category = "Common", id = "skull2021" },
    ["skulls"] = { name = "Skulls", value = 0, category = "Common", id = "skulls" },
    ["skulls_k_2021"] = { name = "Skulls K 2021", value = 0, category = "Common", id = "skulls_k_2021" },
    ["skyline_k_2025"] = { name = "Skyline K 2025", value = 0, category = "Common", id = "skyline_k_2025" },
    ["slashed_k_2020"] = { name = "Slashed K 2020", value = 0, category = "Common", id = "slashed_k_2020" },
    ["slasher"] = { name = "Slasher", value = 20, category = "Godly", id = "slasher" },
    ["slasherchroma"] = { name = "Slasherchroma", value = 0, category = "Godly", id = "slasherchroma" },
    ["slate"] = { name = "Slate", value = 0, category = "Common", id = "slate" },
    ["sleigh_k_2024"] = { name = "Sleigh K 2024", value = 0, category = "Common", id = "sleigh_k_2024" },
    ["slimeg"] = { name = "Slimeg", value = 0, category = "Common", id = "slimeg" },
    ["slimek"] = { name = "Slimek", value = 0, category = "Common", id = "slimek" },
    ["slimyk"] = { name = "Slimyk", value = 0, category = "Common", id = "slimyk" },
    ["snakebiteg"] = { name = "Snakebiteg", value = 0, category = "Common", id = "snakebiteg" },
    ["snakebitek"] = { name = "Snakebitek", value = 0, category = "Common", id = "snakebitek" },
    ["snoop"] = { name = "Snoop", value = 0, category = "Common", id = "snoop" },
    ["snowball_g_2025"] = { name = "Snowball G 2025", value = 0, category = "Common", id = "snowball_g_2025" },
    ["snowball_k_2025"] = { name = "Snowball K 2025", value = 0, category = "Common", id = "snowball_k_2025" },
    ["snowbear2021"] = { name = "Snowbear2021", value = 0, category = "Pet", id = "snowbear2021" },
    ["snowcannon"] = { name = "Snowcannon", value = 260, category = "Godly", id = "snowcannon" },
    ["snowcannonchroma"] = { name = "Snowcannonchroma", value = 0, category = "Godly", id = "snowcannonchroma" },
    ["snowdagger"] = { name = "Snowdagger", value = 0, category = "Godly", id = "snowdagger" },
    ["snowdaggerchroma"] = { name = "Snowdaggerchroma", value = 0, category = "Godly", id = "snowdaggerchroma" },
    ["snowfall_k_2023"] = { name = "Snowfall K 2023", value = 0, category = "Common", id = "snowfall_k_2023" },
    ["snowflake"] = { name = "Snowflake", value = 0, category = "Common", id = "snowflake" },
    ["snowflake_g_2022"] = { name = "Snowflake G 2022", value = 0, category = "Common", id = "snowflake_g_2022" },
    ["snowflake_g_2023"] = { name = "Snowflake G 2023", value = 10, category = "Common", id = "snowflake_g_2023" },
    ["snowflake_k_2018"] = { name = "Snowflake K 2018", value = 0, category = "Common", id = "snowflake_k_2018" },
    ["snowflake_k_2022"] = { name = "Snowflake K 2022", value = 0, category = "Common", id = "snowflake_k_2022" },
    ["snowflakekey"] = { name = "Snowflakekey", value = 0, category = "Common", id = "snowflakekey" },
    ["snowflakes_g_2019"] = { name = "Snowflakes G 2019", value = 0, category = "Common", id = "snowflakes_g_2019" },
    ["snowflakes_k_2019"] = { name = "Snowflakes K 2019", value = 0, category = "Common", id = "snowflakes_k_2019" },
    ["snowflakes_k_2020"] = { name = "Snowflakes K 2020", value = 0, category = "Common", id = "snowflakes_k_2020" },
    ["snowglobe_k_2023"] = { name = "Snowglobe K 2023", value = 0, category = "Common", id = "snowglobe_k_2023" },
    ["snowman"] = { name = "Snowman", value = 0, category = "Common", id = "snowman" },
    ["snowman_g_2018"] = { name = "Snowman G 2018", value = 0, category = "Common", id = "snowman_g_2018" },
    ["snowman_g_2021"] = { name = "Snowman G 2021", value = 0, category = "Common", id = "snowman_g_2021" },
    ["snowman_g_2022"] = { name = "Snowman G 2022", value = 0, category = "Common", id = "snowman_g_2022" },
    ["snowman_g_2023"] = { name = "Snowman G 2023", value = 0, category = "Common", id = "snowman_g_2023" },
    ["snowman_k_2018"] = { name = "Snowman K 2018", value = 0, category = "Common", id = "snowman_k_2018" },
    ["snowman_k_2021"] = { name = "Snowman K 2021", value = 0, category = "Common", id = "snowman_k_2021" },
    ["snowman_k_2022"] = { name = "Snowman K 2022", value = 0, category = "Common", id = "snowman_k_2022" },
    ["snowman_k_2024"] = { name = "Snowman K 2024", value = 0, category = "Common", id = "snowman_k_2024" },
    ["snowman2020"] = { name = "Snowman2020", value = 0, category = "Common", id = "snowman2020" },
    ["snowmangun"] = { name = "Snowmangun", value = 0, category = "Gun", id = "snowmangun" },
    ["snowstorm"] = { name = "Snowstorm", value = 150, category = "Godly", id = "snowstorm" },
    ["snowstormchroma"] = { name = "Snowstormchroma", value = 0, category = "Godly", id = "snowstormchroma" },
    ["snowy"] = { name = "Snowy", value = 0, category = "Common", id = "snowy" },
    ["snowy2017"] = { name = "Snowy2017", value = 0, category = "Common", id = "snowy2017" },
    ["soda_g_2025"] = { name = "Soda G 2025", value = 0, category = "Common", id = "soda_g_2025" },
    ["soda_k_2025"] = { name = "Soda K 2025", value = 0, category = "Common", id = "soda_k_2025" },
    ["sorry"] = { name = "Sorry", value = 0, category = "Common", id = "sorry" },
    ["space"] = { name = "Space", value = 0, category = "Common", id = "space" },
    ["sparkle"] = { name = "Sparkle", value = 0, category = "Common", id = "sparkle" },
    ["sparkle1"] = { name = "Sparkle1", value = 0, category = "Common", id = "sparkle1" },
    ["sparkle10"] = { name = "Sparkle10", value = 0, category = "Common", id = "sparkle10" },
    ["sparkle2"] = { name = "Sparkle2", value = 0, category = "Common", id = "sparkle2" },
    ["sparkle3"] = { name = "Sparkle3", value = 0, category = "Common", id = "sparkle3" },
    ["sparkle4"] = { name = "Sparkle4", value = 0, category = "Common", id = "sparkle4" },
    ["sparkle5"] = { name = "Sparkle5", value = 0, category = "Common", id = "sparkle5" },
    ["sparkle6"] = { name = "Sparkle6", value = 0, category = "Common", id = "sparkle6" },
    ["sparkle7"] = { name = "Sparkle7", value = 0, category = "Common", id = "sparkle7" },
    ["sparkle8"] = { name = "Sparkle8", value = 0, category = "Common", id = "sparkle8" },
    ["sparkle9"] = { name = "Sparkle9", value = 0, category = "Common", id = "sparkle9" },
    ["spearmint_g_2025"] = { name = "Spearmint G 2025", value = 0, category = "Common", id = "spearmint_g_2025" },
    ["spearmint_k_2025"] = { name = "Spearmint K 2025", value = 0, category = "Common", id = "spearmint_k_2025" },
    ["spectral_g_2021"] = { name = "Spectral G 2021", value = 0, category = "Common", id = "spectral_g_2021" },
    ["spectral_k_2021"] = { name = "Spectral K 2021", value = 0, category = "Common", id = "spectral_k_2021" },
    ["spectre2022"] = { name = "Spectre2022", value = 0, category = "Common", id = "spectre2022" },
    ["spectrum"] = { name = "Spectrum", value = 0, category = "Common", id = "spectrum" },
    ["spider"] = { name = "Spider", value = 10, category = "Godly", id = "spider" },
    ["spider_k_2023"] = { name = "Spider K 2023", value = 0, category = "Godly", id = "spider_k_2023" },
    ["spitfire"] = { name = "Spitfire", value = 0, category = "Common", id = "spitfire" },
    ["splash"] = { name = "Splash", value = 0, category = "Common", id = "splash" },
    ["splash_g"] = { name = "Splash G", value = 0, category = "Common", id = "splash_g" },
    ["splat"] = { name = "Splat", value = 0, category = "Common", id = "splat" },
    ["splatter"] = { name = "Splatter", value = 0, category = "Common", id = "splatter" },
    ["spring_k_2024"] = { name = "Spring K 2024", value = 0, category = "Common", id = "spring_k_2024" },
    ["squire"] = { name = "Squire", value = 0, category = "Common", id = "squire" },
    ["stainless"] = { name = "Stainless", value = 0, category = "Common", id = "stainless" },
    ["stalker"] = { name = "Stalker", value = 0, category = "Common", id = "stalker" },
    ["star"] = { name = "Star", value = 0, category = "Common", id = "star" },
    ["starfish_g_2024"] = { name = "Starfish G 2024", value = 0, category = "Common", id = "starfish_g_2024" },
    ["starfish_k_2024"] = { name = "Starfish K 2024", value = 0, category = "Common", id = "starfish_k_2024" },
    ["starry_g_2020"] = { name = "Starry G 2020", value = 0, category = "Common", id = "starry_g_2020" },
    ["starry_g_2021"] = { name = "Starry G 2021", value = 0, category = "Common", id = "starry_g_2021" },
    ["starry_k_2021"] = { name = "Starry K 2021", value = 0, category = "Common", id = "starry_k_2021" },
    ["stars_g_2023"] = { name = "Stars G 2023", value = 0, category = "Common", id = "stars_g_2023" },
    ["stars_k_2023"] = { name = "Stars K 2023", value = 0, category = "Common", id = "stars_k_2023" },
    ["static"] = { name = "Static", value = 0, category = "Common", id = "static" },
    ["steambird"] = { name = "Steambird", value = 2, category = "Godly", id = "steambird" },
    ["steel_g_2023"] = { name = "Steel G 2023", value = 0, category = "Common", id = "steel_g_2023" },
    ["steel_k_2023"] = { name = "Steel K 2023", value = 0, category = "Common", id = "steel_k_2023" },
    ["stickers_g_2021"] = { name = "Stickers G 2021", value = 0, category = "Common", id = "stickers_g_2021" },
    ["stickers_g_2024"] = { name = "Stickers G 2024", value = 0, category = "Common", id = "stickers_g_2024" },
    ["stickers_g_2025"] = { name = "Stickers G 2025", value = 0, category = "Common", id = "stickers_g_2025" },
    ["stickers_k_2021"] = { name = "Stickers K 2021", value = 0, category = "Common", id = "stickers_k_2021" },
    ["stickers_k_2022"] = { name = "Stickers K 2022", value = 0, category = "Common", id = "stickers_k_2022" },
    ["stickers_k_2024"] = { name = "Stickers K 2024", value = 0, category = "Common", id = "stickers_k_2024" },
    ["stickers_k_2025"] = { name = "Stickers K 2025", value = 0, category = "Common", id = "stickers_k_2025" },
    ["stickers_x_g_2024"] = { name = "Stickers X G 2024", value = 0, category = "Common", id = "stickers_x_g_2024" },
    ["stickers_x_k_2024"] = { name = "Stickers X K 2024", value = 0, category = "Common", id = "stickers_x_k_2024" },
    ["stickersh_k_2025"] = { name = "Stickersh K 2025", value = 0, category = "Common", id = "stickersh_k_2025" },
    ["stickerst2025"] = { name = "Stickerst2025", value = 0, category = "Common", id = "stickerst2025" },
    ["stickersx_g_2022"] = { name = "Stickersx G 2022", value = 0, category = "Common", id = "stickersx_g_2022" },
    ["stickersx_g_2025"] = { name = "Stickersx G 2025", value = 0, category = "Common", id = "stickersx_g_2025" },
    ["stickersx_k_2022"] = { name = "Stickersx K 2022", value = 0, category = "Common", id = "stickersx_k_2022" },
    ["stickersx_k_2025"] = { name = "Stickersx K 2025", value = 0, category = "Common", id = "stickersx_k_2025" },
    ["stickersx25"] = { name = "Stickersx25", value = 0, category = "Common", id = "stickersx25" },
    ["stockings_g_2022"] = { name = "Stockings G 2022", value = 0, category = "Common", id = "stockings_g_2022" },
    ["stockings_g_2024"] = { name = "Stockings G 2024", value = 0, category = "Common", id = "stockings_g_2024" },
    ["stockings_k_2020"] = { name = "Stockings K 2020", value = 0, category = "Common", id = "stockings_k_2020" },
    ["stockings_k_2022"] = { name = "Stockings K 2022", value = 0, category = "Common", id = "stockings_k_2022" },
    ["storm_k_2024"] = { name = "Storm K 2024", value = 0, category = "Common", id = "storm_k_2024" },
    ["striped_g_2025"] = { name = "Striped G 2025", value = 0, category = "Common", id = "striped_g_2025" },
    ["striped_k_2025"] = { name = "Striped K 2025", value = 0, category = "Common", id = "striped_k_2025" },
    ["sub"] = { name = "Sub", value = 0, category = "Common", id = "sub" },
    ["sugar"] = { name = "Sugar", value = 60, category = "Godly", id = "sugar" },
    ["summer_stickers_g_2023"] = { name = "Summer Stickers G 2023", value = 0, category = "Common", id = "summer_stickers_g_2023" },
    ["summer_stickers_k_2023"] = { name = "Summer Stickers K 2023", value = 0, category = "Common", id = "summer_stickers_k_2023" },
    ["sunny_g_2025"] = { name = "Sunny G 2025", value = 0, category = "Common", id = "sunny_g_2025" },
    ["sunset_g_2023"] = { name = "Sunset G 2023", value = 0, category = "Godly", id = "sunset_g_2023" },
    ["sunsetgun"] = { name = "Sunsetgun", value = 0, category = "Godly", id = "sunsetgun" },
    ["sunsetgunchroma"] = { name = "Sunsetgunchroma", value = 0, category = "Godly", id = "sunsetgunchroma" },
    ["sunsetknife"] = { name = "Sunsetknife", value = 0, category = "Godly", id = "sunsetknife" },
    ["sunsetknifechroma"] = { name = "Sunsetknifechroma", value = 0, category = "Godly", id = "sunsetknifechroma" },
    ["survivors_k_2022"] = { name = "Survivors K 2022", value = 0, category = "Common", id = "survivors_k_2022" },
    ["sweater"] = { name = "Sweater", value = 0, category = "Common", id = "sweater" },
    ["sweater_g_2018"] = { name = "Sweater G 2018", value = 0, category = "Common", id = "sweater_g_2018" },
    ["sweater_g_2025"] = { name = "Sweater G 2025", value = 0, category = "Common", id = "sweater_g_2025" },
    ["sweater_k_2018"] = { name = "Sweater K 2018", value = 0, category = "Common", id = "sweater_k_2018" },
    ["Sweet"] = { name = "Sweet", value = 0, category = "Common", id = "Sweet" },
    ["sweetheart"] = { name = "Sweetheart", value = 0, category = "Common", id = "sweetheart" },
    ["swirl_k_2021"] = { name = "Swirl K 2021", value = 0, category = "Common", id = "swirl_k_2021" },
    ["swirlyaxe"] = { name = "Swirlyaxe", value = 0, category = "Ancient", id = "swirlyaxe" },
    ["swirlyblade"] = { name = "Swirlyblade", value = 0, category = "Knife", id = "swirlyblade" },
    ["swirlygun"] = { name = "Swirlygun", value = 0, category = "Gun", id = "swirlygun" },
    ["swirlygunchroma"] = { name = "Swirlygunchroma", value = 0, category = "Chroma", id = "swirlygunchroma" },
    ["tailslide"] = { name = "Tailslide", value = 0, category = "Common", id = "tailslide" },
    ["tankie"] = { name = "Tankie", value = 0, category = "Common", id = "tankie" },
    ["Teddy2023"] = { name = "Teddy2023", value = 0, category = "Common", id = "Teddy2023" },
    ["theseer"] = { name = "Theseer", value = 0, category = "Godly", id = "theseer" },
    ["tides"] = { name = "Tides", value = 10, category = "Godly", id = "tides" },
    ["tideschroma"] = { name = "Tideschroma", value = 0, category = "Godly", id = "tideschroma" },
    ["tiger"] = { name = "Tiger", value = 0, category = "Common", id = "tiger" },
    ["timeknife"] = { name = "Timeknife", value = 0, category = "Vintage", id = "timeknife" },
    ["tnl"] = { name = "Tnl", value = 0, category = "Common", id = "tnl" },
    ["toxicg"] = { name = "Toxicg", value = 0, category = "Common", id = "toxicg" },
    ["toxick"] = { name = "Toxick", value = 0, category = "Common", id = "toxick" },
    ["toy_g_2023"] = { name = "Toy G 2023", value = 0, category = "Common", id = "toy_g_2023" },
    ["toy_k_2023"] = { name = "Toy K 2023", value = 0, category = "Common", id = "toy_k_2023" },
    ["traveler_g_2023"] = { name = "Traveler G 2023", value = 0, category = "Common", id = "traveler_g_2023" },
    ["traveler_k_2023"] = { name = "Traveler K 2023", value = 0, category = "Common", id = "traveler_k_2023" },
    ["traveleraxe"] = { name = "Traveleraxe", value = 0, category = "Ancient", id = "traveleraxe" },
    ["travelergun"] = { name = "Travelergun", value = 0, category = "Godly", id = "travelergun" },
    ["travelergunchroma"] = { name = "Travelergunchroma", value = 0, category = "Godly", id = "travelergunchroma" },
    ["traveller"] = { name = "Traveller", value = 1, category = "Godly", id = "traveller" },
    ["Treat"] = { name = "Treat", value = 0, category = "Common", id = "Treat" },
    ["treats_g_2025"] = { name = "Treats G 2025", value = 0, category = "Common", id = "treats_g_2025" },
    ["treats_k_2025"] = { name = "Treats K 2025", value = 0, category = "Common", id = "treats_k_2025" },
    ["tree"] = { name = "Tree", value = 0, category = "Common", id = "tree" },
    ["tree_g_2022"] = { name = "Tree G 2022", value = 0, category = "Common", id = "tree_g_2022" },
    ["tree_k_2021"] = { name = "Tree K 2021", value = 0, category = "Common", id = "tree_k_2021" },
    ["tree_k_2022"] = { name = "Tree K 2022", value = 0, category = "Common", id = "tree_k_2022" },
    ["tree_k_2023"] = { name = "Tree K 2023", value = 0, category = "Common", id = "tree_k_2023" },
    ["tree2017"] = { name = "Tree2017", value = 0, category = "Common", id = "tree2017" },
    ["treegun"] = { name = "Treegun", value = 0, category = "Gun", id = "treegun" },
    ["treegun2023"] = { name = "Treegun2023", value = 0, category = "Gun", id = "treegun2023" },
    ["treegun2023chroma"] = { name = "Treegun2023chroma", value = 0, category = "Chroma", id = "treegun2023chroma" },
    ["treeknife2023"] = { name = "Treeknife2023", value = 0, category = "Knife", id = "treeknife2023" },
    ["treeknife2023chroma"] = { name = "Treeknife2023chroma", value = 0, category = "Chroma", id = "treeknife2023chroma" },
    ["trees_k_2020"] = { name = "Trees K 2020", value = 0, category = "Common", id = "trees_k_2020" },
    ["tropical_k_2025"] = { name = "Tropical K 2025", value = 0, category = "Common", id = "tropical_k_2025" },
    ["tulip"] = { name = "Tulip", value = 0, category = "Common", id = "tulip" },
    ["turkey2023"] = { name = "Turkey2023", value = 0, category = "Godly", id = "turkey2023" },
    ["turtle_k_2024"] = { name = "Turtle K 2024", value = 0, category = "Common", id = "turtle_k_2024" },
    ["ufo"] = { name = "Ufo", value = 0, category = "Common", id = "ufo" },
    ["ufoknife"] = { name = "Ufoknife", value = 0, category = "Knife", id = "ufoknife" },
    ["ufoknifechroma"] = { name = "Ufoknifechroma", value = 0, category = "Chroma", id = "ufoknifechroma" },
    ["ufos_g_2025"] = { name = "Ufos G 2025", value = 0, category = "Common", id = "ufos_g_2025" },
    ["ufos_k_2025"] = { name = "Ufos K 2025", value = 0, category = "Common", id = "ufos_k_2025" },
    ["universe"] = { name = "Universe", value = 0, category = "Common", id = "universe" },
    ["valentine"] = { name = "Valentine", value = 0, category = "Common", id = "valentine" },
    ["vampire"] = { name = "Vampire", value = 0, category = "Common", id = "vampire" },
    ["vampire_g_2022"] = { name = "Vampire G 2022", value = 0, category = "Common", id = "vampire_g_2022" },
    ["vampire_k_2022"] = { name = "Vampire K 2022", value = 0, category = "Common", id = "vampire_k_2022" },
    ["vampireaxe"] = { name = "Vampireaxe", value = 0, category = "Ancient", id = "vampireaxe" },
    ["vampirebat"] = { name = "Vampirebat", value = 0, category = "Pet", id = "vampirebat" },
    ["vampireg2018"] = { name = "Vampireg2018", value = 0, category = "Common", id = "vampireg2018" },
    ["vampiregun"] = { name = "Vampiregun", value = 0, category = "Gun", id = "vampiregun" },
    ["vampiregunchroma"] = { name = "Vampiregunchroma", value = 0, category = "Chroma", id = "vampiregunchroma" },
    ["vampirek2018"] = { name = "Vampirek2018", value = 0, category = "Common", id = "vampirek2018" },
    ["vampiresedge"] = { name = "Vampiresedge", value = 0, category = "Knife", id = "vampiresedge" },
    ["vines_g_2023"] = { name = "Vines G 2023", value = 0, category = "Common", id = "vines_g_2023" },
    ["vines_k_2023"] = { name = "Vines K 2023", value = 0, category = "Common", id = "vines_k_2023" },
    ["viper"] = { name = "Viper", value = 0, category = "Common", id = "viper" },
    ["virtual"] = { name = "Virtual", value = 0, category = "Common", id = "virtual" },
    ["voidrbx"] = { name = "Voidrbx", value = 0, category = "Common", id = "voidrbx" },
    ["vortex"] = { name = "Vortex", value = 0, category = "Common", id = "vortex" },
    ["wanwood"] = { name = "Wanwood", value = 0, category = "Common", id = "wanwood" },
    ["watcher_g_2021"] = { name = "Watcher G 2021", value = 0, category = "Common", id = "watcher_g_2021" },
    ["watcher_k_2021"] = { name = "Watcher K 2021", value = 0, category = "Common", id = "watcher_k_2021" },
    ["waterballoons_g_2024"] = { name = "Waterballoons G 2024", value = 115, category = "Godly", id = "waterballoons_g_2024" },
    ["watergun"] = { name = "Watergun", value = 0, category = "Gun", id = "watergun" },
    ["watergunchroma"] = { name = "Watergunchroma", value = 0, category = "Chroma", id = "watergunchroma" },
    ["waves_k"] = { name = "Waves K", value = 0, category = "Common", id = "waves_k" },
    ["waves_k_2024"] = { name = "Waves K 2024", value = 0, category = "Common", id = "waves_k_2024" },
    ["wavy_g_2024"] = { name = "Wavy G 2024", value = 0, category = "Common", id = "wavy_g_2024" },
    ["wavy_k_2024"] = { name = "Wavy K 2024", value = 0, category = "Common", id = "wavy_k_2024" },
    ["web"] = { name = "Web", value = 0, category = "Common", id = "web" },
    ["webbedg"] = { name = "Webbedg", value = 0, category = "Common", id = "webbedg" },
    ["webbedk"] = { name = "Webbedk", value = 0, category = "Common", id = "webbedk" },
    ["webs"] = { name = "Webs", value = 0, category = "Common", id = "webs" },
    ["webs_g_2022"] = { name = "Webs G 2022", value = 0, category = "Common", id = "webs_g_2022" },
    ["whiteout"] = { name = "Whiteout", value = 0, category = "Common", id = "whiteout" },
    ["wintersedge"] = { name = "Wintersedge", value = 0, category = "Godly", id = "wintersedge" },
    ["witch"] = { name = "Witch", value = 0, category = "Common", id = "witch" },
    ["witch_k_2022"] = { name = "Witch K 2022", value = 0, category = "Common", id = "witch_k_2022" },
    ["witchbrew_k_2024"] = { name = "Witchbrew K 2024", value = 0, category = "Common", id = "witchbrew_k_2024" },
    ["witched"] = { name = "Witched", value = 0, category = "Common", id = "witched" },
    ["wolf"] = { name = "Wolf", value = 0, category = "Common", id = "wolf" },
    ["wood_k_2023"] = { name = "Wood K 2023", value = 0, category = "Common", id = "wood_k_2023" },
    ["wooden"] = { name = "Wooden", value = 0, category = "Common", id = "wooden" },
    ["wraith_g_2022"] = { name = "Wraith G 2022", value = 0, category = "Common", id = "wraith_g_2022" },
    ["wraith_k_2022"] = { name = "Wraith K 2022", value = 0, category = "Common", id = "wraith_k_2022" },
    ["wraithgun"] = { name = "Wraithgun", value = 0, category = "Gun", id = "wraithgun" },
    ["wraithknife"] = { name = "Wraithknife", value = 0, category = "Knife", id = "wraithknife" },
    ["wrappaperboxblue"] = { name = "Wrappaperboxblue", value = 0, category = "Common", id = "wrappaperboxblue" },
    ["wrappaperboxgold"] = { name = "Wrappaperboxgold", value = 0, category = "Common", id = "wrappaperboxgold" },
    ["wrappaperboxgreen"] = { name = "Wrappaperboxgreen", value = 0, category = "Common", id = "wrappaperboxgreen" },
    ["wrappaperboxpurple"] = { name = "Wrappaperboxpurple", value = 0, category = "Common", id = "wrappaperboxpurple" },
    ["wrappaperboxred"] = { name = "Wrappaperboxred", value = 0, category = "Common", id = "wrappaperboxred" },
    ["wrappaperboxultra"] = { name = "Wrappaperboxultra", value = 0, category = "Common", id = "wrappaperboxultra" },
    ["wrapped"] = { name = "Wrapped", value = 0, category = "Common", id = "wrapped" },
    ["wrapped_g_2018"] = { name = "Wrapped G 2018", value = 0, category = "Common", id = "wrapped_g_2018" },
    ["wrapped_g_2024"] = { name = "Wrapped G 2024", value = 0, category = "Common", id = "wrapped_g_2024" },
    ["wrapped_k_2018"] = { name = "Wrapped K 2018", value = 0, category = "Common", id = "wrapped_k_2018" },
    ["wrapped_k_2022"] = { name = "Wrapped K 2022", value = 0, category = "Common", id = "wrapped_k_2022" },
    ["wrapped_k_2024"] = { name = "Wrapped K 2024", value = 0, category = "Common", id = "wrapped_k_2024" },
    ["wrappedgun"] = { name = "Wrappedgun", value = 0, category = "Gun", id = "wrappedgun" },
    ["wreaths_k_2024"] = { name = "Wreaths K 2024", value = 0, category = "Common", id = "wreaths_k_2024" },
    ["xbox"] = { name = "Xbox", value = 0, category = "Common", id = "xbox" },
    ["xeno_g_2025"] = { name = "Xeno G 2025", value = 0, category = "Common", id = "xeno_g_2025" },
    ["xeno_k_2025"] = { name = "Xeno K 2025", value = 0, category = "Common", id = "xeno_k_2025" },
    ["xenogun"] = { name = "Xenogun", value = 0, category = "Gun", id = "xenogun" },
    ["xenoknife"] = { name = "Xenoknife", value = 150, category = "Godly", id = "xenoknife" },
    ["xmas"] = { name = "Xmas", value = 8, category = "Godly", id = "xmas" },
    ["xmasstickers_g_2021"] = { name = "Xmasstickers G 2021", value = 0, category = "Godly", id = "xmasstickers_g_2021" },
    ["xmasstickers_k_2021"] = { name = "Xmasstickers K 2021", value = 0, category = "Godly", id = "xmasstickers_k_2021" },
    ["yellowseer"] = { name = "Yellowseer", value = 0, category = "Godly", id = "yellowseer" },
    ["zombie"] = { name = "Zombie", value = 0, category = "Common", id = "zombie" },
    ["zombie_k_2021"] = { name = "Zombie K 2021", value = 0, category = "Common", id = "zombie_k_2021" },
    ["zombie_k_2023"] = { name = "Zombie K 2023", value = 0, category = "Common", id = "zombie_k_2023" },
    ["zombiebat"] = { name = "Zombiebat", value = 0, category = "Pet", id = "zombiebat" },
    ["zombiedog"] = { name = "Zombiedog", value = 0, category = "Pet", id = "zombiedog" },
    ["zombieg2018"] = { name = "Zombieg2018", value = 0, category = "Common", id = "zombieg2018" },
    ["zombiek2018"] = { name = "Zombiek2018", value = 0, category = "Common", id = "zombiek2018" },
    ["zombifiedg"] = { name = "Zombifiedg", value = 0, category = "Common", id = "zombifiedg" },
    ["zombifiedk"] = { name = "Zombifiedk", value = 0, category = "Common", id = "zombifiedk" },
}
