export type Rarity = "chroma" | "ancient" | "godly" | "legendary" | "unique" | "rare" | "uncommon" | "common" | "vintage" | "halloween";
export type ItemType = "knife" | "gun";

export interface MM2Item {
  id?: number | string;
  name: string;
  display_name?: string;
  value: number;
  rarity: Rarity;
  type: ItemType;
  image: string;
  slug: string;
}

export const mm2Items: MM2Item[] = [
  { name: "Chroma Traveler&#x27;s Gun", value: 130000, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/travelergunchroma.png", slug: "travelergunchroma" },
  { name: "Chroma Evergun", value: 72000, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/treegun2023chroma.png", slug: "treegun2023chroma" },
  { name: "Chroma Evergreen", value: 51000, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/treeknife2023chroma.png", slug: "treeknife2023chroma" },
  { name: "Chroma Bauble", value: 50000, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/baublechroma.png", slug: "baublechroma" },
  { name: "Chroma Constellation", value: 35000, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/constellationchroma.png", slug: "constellationchroma" },
  { name: "Chroma Vampire&#x27;s Gun", value: 31000, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/vampiregunchroma.png", slug: "vampiregunchroma" },
  { name: "Chroma Alienbeam", value: 14500, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/ufoknifechroma.png", slug: "ufoknifechroma" },
  { name: "Gingerscope", value: 14000, rarity: "ancient", type: "gun", image: "https://cdn.bloxluck.com/item-images/gingerscope.png", slug: "gingerscope" },
  { name: "Chroma Blizzard", value: 13000, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/blizzardchroma.png", slug: "blizzardchroma" },
  { name: "Chroma Raygun", value: 10500, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/raygunchroma.png", slug: "raygunchroma" },
  { name: "Chroma Snowstorm", value: 9000, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowstormchroma.png", slug: "snowstormchroma" },
  { name: "Chroma Snow Dagger", value: 8000, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowdaggerchroma.png", slug: "snowdaggerchroma" },
  { name: "Chroma Snowcannon", value: 7500, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/snowcannonchroma.png", slug: "snowcannonchroma" },
  { name: "Chroma Sunrise", value: 7300, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/sunsetgunchroma.png", slug: "sunsetgunchroma" },
  { name: "Traveler&#x27;s Axe", value: 7300, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/traveleraxe.png", slug: "traveleraxe" },
  { name: "Evergun", value: 4200, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/treegun2023.png", slug: "treegun2023" },
  { name: "Chroma Sunset", value: 4100, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/sunsetknifechroma.png", slug: "sunsetknifechroma" },
  { name: "Traveler&#x27;s Gun", value: 4000, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/travelergun.png", slug: "travelergun" },
  { name: "Chroma Ornament", value: 3500, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/baubleknifechroma.png", slug: "baubleknifechroma" },
  { name: "Constellation", value: 3300, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/constellation.png", slug: "constellation" },
  { name: "Evergreen", value: 3300, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/treeknife2023.png", slug: "treeknife2023" },
  { name: "Chroma Watergun", value: 2750, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/watergunchroma.png", slug: "watergunchroma" },
  { name: "Vampire&#x27;s Gun", value: 1825, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/vampiregun.png", slug: "vampiregun" },
  { name: "Turkey", value: 1800, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/turkey2023.png", slug: "turkey2023" },
  { name: "Celestial", value: 1775, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/celestial.png", slug: "celestial" },
  { name: "Bauble", value: 900, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/bauble.png", slug: "bauble" },
  { name: "Corrupt", value: 825, rarity: "unique", type: "knife", image: "https://cdn.bloxluck.com/item-images/sorry.png", slug: "sorry" },
  { name: "Vampire&#x27;s Axe", value: 800, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/vampireaxe.png", slug: "vampireaxe" },
  { name: "Alienbeam", value: 725, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/ufoknife.png", slug: "ufoknife" },
  { name: "Raygun", value: 475, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/raygun.png", slug: "raygun" },
  { name: "Harvester", value: 425, rarity: "ancient", type: "gun", image: "https://cdn.bloxluck.com/item-images/harvester.png", slug: "harvester" },
  { name: "Icepiercer", value: 350, rarity: "ancient", type: "gun", image: "https://cdn.bloxluck.com/item-images/icepiercer.png", slug: "icepiercer" },
  { name: "Sunrise", value: 270, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/sunsetgun.png", slug: "sunsetgun" },
  { name: "Soul", value: 270, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/wraithgun.png", slug: "wraithgun" },
  { name: "Spirit", value: 265, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/wraithknife.png", slug: "wraithknife" },
  { name: "Snowcannon", value: 260, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/snowcannon.png", slug: "snowcannon" },
  { name: "Snow Dagger", value: 260, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowdagger.png", slug: "snowdagger" },
  { name: "Flora", value: 215, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/flora.png", slug: "flora" },
  { name: "Bloom", value: 205, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/bloom.png", slug: "bloom" },
  { name: "Sunset", value: 180, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/sunsetknife.png", slug: "sunsetknife" },
  { name: "Candy", value: 170, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/candy.png", slug: "candy" },
  { name: "Xenoknife", value: 150, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/xenoknife.png", slug: "xenoknife" },
  { name: "Snowstorm", value: 150, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowstorm.png", slug: "snowstorm" },
  { name: "Xenoshot", value: 150, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/xenogun.png", slug: "xenogun" },
  { name: "Blizzard", value: 150, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/blizzard.png", slug: "blizzard" },
  { name: "Cane", value: 150, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/cane-k-2018.png", slug: "cane-k-2018" },
  { name: "Flowerwood Gun", value: 150, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/flowerwoodgun.png", slug: "flowerwoodgun" },
  { name: "Flowerwood", value: 145, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/flowerwoodknife.png", slug: "flowerwoodknife" },
  { name: "Ocean", value: 145, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/ocean-g.png", slug: "ocean-g" },
  { name: "Waves", value: 140, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/waves-k.png", slug: "waves-k" },
  { name: "Latte", value: 125, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/latte-k-2023.png", slug: "latte-k-2023" },
  { name: "Icebreaker", value: 115, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/icebreaker.png", slug: "icebreaker" },
  { name: "Watergun", value: 115, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/watergun.png", slug: "watergun" },
  { name: "Borealis", value: 105, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/auroragun.png", slug: "auroragun" },
  { name: "Australis", value: 100, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/auroraknife.png", slug: "auroraknife" },
  { name: "Chroma Darkbringer", value: 95, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/chromadarkbringer.png", slug: "chromadarkbringer" },
  { name: "Chroma Lightbringer", value: 90, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/chromalightbringer.png", slug: "chromalightbringer" },
  { name: "Chroma Candleflame", value: 70, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/candleflamechroma.png", slug: "candleflamechroma" },
  { name: "Glitch1", value: 70, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/batwing.png", slug: "batwing" },
  { name: "Sugar", value: 60, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/sugar.png", slug: "sugar" },
  { name: "Luger", value: 60, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/luger.png", slug: "luger" },
  { name: "Chroma Luger", value: 60, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/lugerchroma.png", slug: "lugerchroma" },
  { name: "Iceblaster", value: 60, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/iceblaster.png", slug: "iceblaster" },
  { name: "Chroma Elderwood Blade", value: 60, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/elderwoodknifechroma.png", slug: "elderwoodknifechroma" },
  { name: "Chroma Swirly Gun", value: 60, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/swirlygunchroma.png", slug: "swirlygunchroma" },
  { name: "Chroma Cookiecane", value: 60, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingermint-kchroma.png", slug: "gingermint-kchroma" },
  { name: "Pearl", value: 60, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/pearl-k.png", slug: "pearl-k" },
  { name: "Pearlshine", value: 60, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/pearl-g.png", slug: "pearl-g" },
  { name: "Batwing", value: 57, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/scythe.png", slug: "scythe" },
  { name: "Elderwood Revolver", value: 55, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/elderwoodgun.png", slug: "elderwoodgun" },
  { name: "Darkbringer", value: 55, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/darkbringer.png", slug: "darkbringer" },
  { name: "Candleflame", value: 55, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/candleflame.png", slug: "candleflame" },
  { name: "Swirly Axe", value: 55, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/swirlyaxe.png", slug: "swirlyaxe" },
  { name: "Elderwood Scythe", value: 55, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/elderwoodscythe.png", slug: "elderwoodscythe" },
  { name: "Chroma Laser", value: 55, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/laserchroma.png", slug: "laserchroma" },
  { name: "Lightbringer", value: 50, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/lightbringer.png", slug: "lightbringer" },
  { name: "Chroma Deathshard", value: 50, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/deathshardchroma.png", slug: "deathshardchroma" },
  { name: "Chroma Slasher", value: 50, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/slasherchroma.png", slug: "slasherchroma" },
  { name: "Red Luger", value: 50, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/redluger.png", slug: "redluger" },
  { name: "Ornament", value: 50, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/baubleknife.png", slug: "baubleknife" },
  { name: "Chroma Shark", value: 50, rarity: "chroma", type: "gun", image: "https://cdn.bloxluck.com/item-images/sharkchroma.png", slug: "sharkchroma" },
  { name: "Chroma Gemstone", value: 45, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/gemstonechroma.png", slug: "gemstonechroma" },
  { name: "Chroma Heat", value: 45, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/heatchroma.png", slug: "heatchroma" },
  { name: "Hallowscythe", value: 45, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/hallowscythe.png", slug: "hallowscythe" },
  { name: "Chroma Fang", value: 45, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/fangchroma.png", slug: "fangchroma" },
  { name: "Chroma Tides", value: 42, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/tideschroma.png", slug: "tideschroma" },
  { name: "Cotton Candy", value: 40, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/cottoncandy.png", slug: "cottoncandy" },
  { name: "Chroma Seer", value: 40, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/seerchroma.png", slug: "seerchroma" },
  { name: "Swirly Gun", value: 40, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/swirlygun.png", slug: "swirlygun" },
  { name: "Chroma Boneblade", value: 40, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/bonebladechroma.png", slug: "bonebladechroma" },
  { name: "Chroma Gingerblade", value: 40, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingerbladechroma.png", slug: "gingerbladechroma" },
  { name: "JD", value: 40, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/jd.png", slug: "jd" },
  { name: "Chroma Saw", value: 40, rarity: "chroma", type: "knife", image: "https://cdn.bloxluck.com/item-images/sawchroma.png", slug: "sawchroma" },
  { name: "Green Luger", value: 30, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/greenluger.png", slug: "greenluger" },
  { name: "Hallowgun", value: 27, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/hallowgun.png", slug: "hallowgun" },
  { name: "Laser", value: 27, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/laser.png", slug: "laser" },
  { name: "Plasmabeam", value: 25, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/plasmabeam.png", slug: "plasmabeam" },
  { name: "Amerilaser", value: 25, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/amerilaser.png", slug: "amerilaser" },
  { name: "Plasmablade", value: 25, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/plasmablade.png", slug: "plasmablade" },
  { name: "Iceflake", value: 25, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/iceflake.png", slug: "iceflake" },
  { name: "Swirly Blade", value: 25, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/swirlyblade.png", slug: "swirlyblade" },
  { name: "Icebeam", value: 25, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/icebeam.png", slug: "icebeam" },
  { name: "Shark", value: 23, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/shark.png", slug: "shark" },
  { name: "Nightblade", value: 22, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/nightblade.png", slug: "nightblade" },
  { name: "Blaster", value: 20, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/blaster.png", slug: "blaster" },
  { name: "Logchopper", value: 20, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/logchopper.png", slug: "logchopper" },
  { name: "Minty", value: 20, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/minty.png", slug: "minty" },
  { name: "Ginger Luger", value: 20, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/gingerluger.png", slug: "gingerluger" },
  { name: "Pixel", value: 20, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/pixel.png", slug: "pixel" },
  { name: "Slasher", value: 20, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/slasher.png", slug: "slasher" },
  { name: "Old Glory", value: 18, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/americasword.png", slug: "americasword" },
  { name: "Gingerblade", value: 18, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingerblade.png", slug: "gingerblade" },
  { name: "BattleAxe II", value: 18, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/battleaxe2.png", slug: "battleaxe2" },
  { name: "Lugercane", value: 18, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/lugercane.png", slug: "lugercane" },
  { name: "Eternalcane", value: 18, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/eternalcane.png", slug: "eternalcane" },
  { name: "Virtual", value: 17, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/virtual.png", slug: "virtual" },
  { name: "Gemstone", value: 17, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/gemstone.png", slug: "gemstone" },
  { name: "Jinglegun", value: 17, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/jinglegun.png", slug: "jinglegun" },
  { name: "Deathshard", value: 15, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/deathshard.png", slug: "deathshard" },
  { name: "Nebula", value: 15, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/nebula.png", slug: "nebula" },
  { name: "Vampire&#x27;s Edge", value: 15, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/vampiresedge.png", slug: "vampiresedge" },
  { name: "BattleAxe", value: 12, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/battleaxe.png", slug: "battleaxe" },
  { name: "Icewing", value: 12, rarity: "ancient", type: "knife", image: "https://cdn.bloxluck.com/item-images/icewing.png", slug: "icewing" },
  { name: "Chill", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/chill.png", slug: "chill" },
  { name: "Clockwork", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/clockwork.png", slug: "clockwork" },
  { name: "Ghost", value: 10, rarity: "vintage", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghostknife.png", slug: "ghostknife" },
  { name: "Spider", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/spider.png", slug: "spider" },
  { name: "Bioblade", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/bioblade.png", slug: "bioblade" },
  { name: "Eternal III", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/eternal3.png", slug: "eternal3" },
  { name: "Heat", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/heat.png", slug: "heat" },
  { name: "Eternal IV", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/eternal4.png", slug: "eternal4" },
  { name: "Frostsaber", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/frostsaber.png", slug: "frostsaber" },
  { name: "Fang", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/fang.png", slug: "fang" },
  { name: "Tides", value: 10, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/tides.png", slug: "tides" },
  { name: "Snowflake", value: 10, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowflake-k-2018.png", slug: "snowflake-k-2018" },
  { name: "Gifts", value: 10, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/gifts-k-2019.png", slug: "gifts-k-2019" },
  { name: "Hallow&#x27;s Blade", value: 8, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/hallowsblade.png", slug: "hallowsblade" },
  { name: "Blood", value: 8, rarity: "vintage", type: "knife", image: "https://cdn.bloxluck.com/item-images/bloodknife.png", slug: "bloodknife" },
  { name: "Hallow&#x27;s Edge", value: 8, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/hallow.png", slug: "hallow" },
  { name: "Handsaw", value: 8, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/handsaw.png", slug: "handsaw" },
  { name: "Eternal", value: 8, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/eternal.png", slug: "eternal" },
  { name: "Eternal II", value: 8, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/eternal2.png", slug: "eternal2" },
  { name: "Xmas", value: 8, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/xmas.png", slug: "xmas" },
  { name: "Skulls 2019", value: 8, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/skulls.png", slug: "skulls" },
  { name: "Sweater", value: 8, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/sweater-k-2018.png", slug: "sweater-k-2018" },
  { name: "Silent Night", value: 8, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/silentnight-k-2020.png", slug: "silentnight-k-2020" },
  { name: "Ice Dragon", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/icedragon.png", slug: "icedragon" },
  { name: "Ice Shard", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/iceshard.png", slug: "iceshard" },
  { name: "Prismatic", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/prismatic.png", slug: "prismatic" },
  { name: "Pumpking", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/pumpking.png", slug: "pumpking" },
  { name: "Santa&#x27;s Spirit", value: 7, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/santasspirit.png", slug: "santasspirit" },
  { name: "Saw", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/saw.png", slug: "saw" },
  { name: "Frostbite", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/frostbite.png", slug: "frostbite" },
  { name: "Boneblade", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/boneblade.png", slug: "boneblade" },
  { name: "Santa&#x27;s Magic", value: 7, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/santasmagic.png", slug: "santasmagic" },
  { name: "America", value: 7, rarity: "vintage", type: "gun", image: "https://cdn.bloxluck.com/item-images/americagun.png", slug: "americagun" },
  { name: "Ghostblade", value: 7, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghostblade.png", slug: "ghostblade" },
  { name: "Green Marble", value: 7, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/greenmarble.png", slug: "greenmarble" },
  { name: "Shadow", value: 6, rarity: "vintage", type: "knife", image: "https://cdn.bloxluck.com/item-images/shadowknife.png", slug: "shadowknife" },
  { name: "Prince", value: 6, rarity: "vintage", type: "knife", image: "https://cdn.bloxluck.com/item-images/timeknife.png", slug: "timeknife" },
  { name: "Flames", value: 5, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/flames.png", slug: "flames" },
  { name: "Phaser", value: 5, rarity: "vintage", type: "gun", image: "https://cdn.bloxluck.com/item-images/phaser.png", slug: "phaser" },
  { name: "Eggblade", value: 5, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/eggblade.png", slug: "eggblade" },
  { name: "Zombie", value: 5, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/zombie.png", slug: "zombie" },
  { name: "Winter&#x27;s Edge", value: 5, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/wintersedge.png", slug: "wintersedge" },
  { name: "Peppermint", value: 4, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/peppermint.png", slug: "peppermint" },
  { name: "Toxic Gun", value: 4, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/toxicg.png", slug: "toxicg" },
  { name: "Wolf", value: 4, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/wolf.png", slug: "wolf" },
  { name: "Cowboy", value: 4, rarity: "vintage", type: "gun", image: "https://cdn.bloxluck.com/item-images/gun1.png", slug: "gun1" },
  { name: "Golden", value: 4, rarity: "vintage", type: "gun", image: "https://cdn.bloxluck.com/item-images/goldengun.png", slug: "goldengun" },
  { name: "Ecto", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ecto.png", slug: "ecto" },
  { name: "Cookieblade", value: 3, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/cookieblade.png", slug: "cookieblade" },
  { name: "Reptile", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/reptile.png", slug: "reptile" },
  { name: "Blue Seer", value: 3, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/blueseer.png", slug: "blueseer" },
  { name: "Splitter", value: 3, rarity: "vintage", type: "knife", image: "https://cdn.bloxluck.com/item-images/knife1.png", slug: "knife1" },
  { name: "Roses", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/roses.png", slug: "roses" },
  { name: "Hearts", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/hearts.png", slug: "hearts" },
  { name: "Elf", value: 3, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/elfgun.png", slug: "elfgun" },
  { name: "Purple Seer", value: 3, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/purpleseer.png", slug: "purpleseer" },
  { name: "Red Seer", value: 3, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/redseer.png", slug: "redseer" },
  { name: "Neon", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/neon.png", slug: "neon" },
  { name: "Orange Marble", value: 3, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/orangemarble.png", slug: "orangemarble" },
  { name: "Witch", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/witch.png", slug: "witch" },
  { name: "Snakebite Gun", value: 3, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/snakebiteg.png", slug: "snakebiteg" },
  { name: "Vampire 2018", value: 3, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/vampirek2018.png", slug: "vampirek2018" },
  { name: "Seer", value: 3, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/theseer.png", slug: "theseer" },
  { name: "Patrick", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/patrick.png", slug: "patrick" },
  { name: "Pine", value: 3, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/pine-k-2019.png", slug: "pine-k-2019" },
  { name: "Frozen", value: 3, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/frozen-k-2019.png", slug: "frozen-k-2019" },
  { name: "Candy Swirl Knife", value: 3, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/candyswirl-k-2019.png", slug: "candyswirl-k-2019" },
  { name: "Aurora Gun 2021", value: 3, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/aurora-g-2021.png", slug: "aurora-g-2021" },
  { name: "Aurora 2019", value: 3, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/aurora-g-2019.png", slug: "aurora-g-2019" },
  { name: "Beach", value: 3, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/beach-k-2023.png", slug: "beach-k-2023" },
  { name: "Valentine", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/valentine.png", slug: "valentine" },
  { name: "Blossom", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/blossom1.png", slug: "blossom" },
  { name: "Orange Seer", value: 2, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/orangeseer.png", slug: "orangeseer" },
  { name: "Jack", value: 2, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/jack.png", slug: "jack" },
  { name: "Yellow Seer", value: 2, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/yellowseer.png", slug: "yellowseer" },
  { name: "Heartblade", value: 2, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/heartblade.png", slug: "heartblade" },
  { name: "Tulip", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/tulip.png", slug: "tulip" },
  { name: "TNL", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/tnl.png", slug: "tnl" },
  { name: "CandyCorn", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/candycorn.png", slug: "candycorn" },
  { name: "Sweetheart", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sweetheart.png", slug: "sweetheart" },
  { name: "Silent Night Gun", value: 2, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/silentnight-g-2020.png", slug: "silentnight-g-2020" },
  { name: "Lights", value: 2, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/lights-k-2019.png", slug: "lights-k-2019" },
  { name: "Frostfade", value: 2, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/frostfade-k-2023.png", slug: "frostfade-k-2023" },
  { name: "Passion", value: 2, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/passion.png", slug: "passion" },
  { name: "Denis", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/denis.png", slug: "denis" },
  { name: "Ornament 2 Knife", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ornament2.png", slug: "ornament2" },
  { name: "Cane 2015", value: 1, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/cane.png", slug: "cane" },
  { name: "Frosty", value: 1, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/frosty.png", slug: "frosty" },
  { name: "Infected", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/infected.png", slug: "infected" },
  { name: "Prism", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/prism.png", slug: "prism" },
  { name: "Sub", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sub.png", slug: "sub" },
  { name: "Goo", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/goo.png", slug: "goo" },
  { name: "2015", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/2015.png", slug: "2015" },
  { name: "Corl", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/corl.png", slug: "corl" },
  { name: "Red Fire", value: 1, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/redfire.png", slug: "redfire" },
  { name: "Carrot", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/carrot.png", slug: "carrot" },
  { name: "Alex", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/alex.png", slug: "alex" },
  { name: "Ornament 2 Gun", value: 1, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/ornament2gun.png", slug: "ornament2gun" },
  { name: "Egg", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/eggs.png", slug: "eggs" },
  { name: "Ornament1", value: 1, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/ornament1gun.png", slug: "ornament1gun" },
  { name: "Ripper", value: 1, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/ripper-k-2020.png", slug: "ripper-k-2020" },
  { name: "Icicles Knife", value: 1, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/icicles-k-2018.png", slug: "icicles-k-2018" },
  { name: "Icicles", value: 1, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/icicles-g-2018.png", slug: "icicles-g-2018" },
  { name: "Cavern", value: 1, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/cavern-g-2019.png", slug: "cavern-g-2019" },
  { name: "Sketchy", value: 1, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sketchyt.png", slug: "sketchyt" },
  { name: "Potion", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/potionk2018.png", slug: "potionk2018" },
  { name: "Snowman Gun", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/snowmangun.png", slug: "snowmangun" },
  { name: "Butterflies", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/butterflies-g-2025.png", slug: "butterflies-g-2025" },
  { name: "Stickers", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/stickersx25.png", slug: "stickersx25" },
  { name: "Wavy", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/wavy-g-2024.png", slug: "wavy-g-2024" },
  { name: "Darksword", value: 0, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/darksword.png", slug: "darksword" },
  { name: "Santa", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/santa2017.png", slug: "santa2017" },
  { name: "Mummy", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/mummy.png", slug: "mummy" },
  { name: "Tree Gun", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/treegun.png", slug: "treegun" },
  { name: "Ginger", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/gingergun.png", slug: "gingergun" },
  { name: "Melon", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/melon.png", slug: "melon" },
  { name: "Marina", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/marina.png", slug: "marina" },
  { name: "Camo", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/camo.png", slug: "camo" },
  { name: "Candy Corn", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/candycorn2019.png", slug: "candycorn2019" },
  { name: "Bats", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/batsk.png", slug: "batsk" },
  { name: "Blue Scratch", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/scratchblue.png", slug: "scratchblue" },
  { name: "Spectre", value: 0, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/spectre2022.png", slug: "spectre2022" },
  { name: "Moons", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/moons.png", slug: "moons" },
  { name: "Pumpkin Patch", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/pumpkinpatch.png", slug: "pumpkinpatch" },
  { name: "Heart", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/heart-k-2023.png", slug: "heart-k-2023" },
  { name: "Damp", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/damp.png", slug: "damp" },
  { name: "Brains", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/brains2019.png", slug: "brains2019" },
  { name: "Witched", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/witched.png", slug: "witched" },
  { name: "Dungeon", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/dungeon.png", slug: "dungeon" },
  { name: "Tailslide", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/tailslide.png", slug: "tailslide" },
  { name: "Asteroid", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/asteroid.png", slug: "asteroid" },
  { name: "Gingerbread", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingerbread2017.png", slug: "gingerbread2017" },
  { name: "Void", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/voidrbx.png", slug: "voidrbx" },
  { name: "Zombified", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/zombifiedg.png", slug: "zombifiedg" },
  { name: "Zombie Knife 2018", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/zombiek2018.png", slug: "zombiek2018" },
  { name: "Glitch2", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/randluger.png", slug: "randluger" },
  { name: "Darkshot", value: 0, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/darkshot.png", slug: "darkshot" },
  { name: "Branches", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/branches.png", slug: "branches" },
  { name: "Tree", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/tree2017.png", slug: "tree2017" },
  { name: "Bacon", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/bacon.png", slug: "bacon" },
  { name: "Potion 2017", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/potion.png", slug: "potion" },
  { name: "Green Fire", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/greenfire.png", slug: "greenfire" },
  { name: "Slimy", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/slimyk.png", slug: "slimyk" },
  { name: "Green Elite", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/elitegreen.png", slug: "elitegreen" },
  { name: "Slime", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/slimeg.png", slug: "slimeg" },
  { name: "Blue", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/chips.png", slug: "chips" },
  { name: "Santa Gun", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/santagun.png", slug: "santagun" },
  { name: "Vampire 2016", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/vampire.png", slug: "vampire" },
  { name: "Jigsaw", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/jigsaw.png", slug: "jigsaw" },
  { name: "Skool", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/skool.png", slug: "skool" },
  { name: "Paper", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/paper.png", slug: "paper" },
  { name: "Wrapped 2015", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/wrapped.png", slug: "wrapped" },
  { name: "Adurite", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/adurite.png", slug: "adurite" },
  { name: "Present", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/present.png", slug: "present" },
  { name: "Caution", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/caution.png", slug: "caution" },
  { name: "Night", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/night.png", slug: "night" },
  { name: "Ollie", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ollie.png", slug: "ollie" },
  { name: "Webbed", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/webbedk.png", slug: "webbedk" },
  { name: "Red Scratch", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/scratch.png", slug: "scratch" },
  { name: "Snowy", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowy2017.png", slug: "snowy2017" },
  { name: "Toxic", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/toxick.png", slug: "toxick" },
  { name: "Bats 2016", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/bats.png", slug: "bats" },
  { name: "Stalker", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/stalker.png", slug: "stalker" },
  { name: "Bleached", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/bleached.png", slug: "bleached" },
  { name: "Bones", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/bones2019.png", slug: "bones2019" },
  { name: "Oily", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/oily.png", slug: "oily" },
  { name: "Webs", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/webs.png", slug: "webs" },
  { name: "Phantom", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/phantom.png", slug: "phantom" },
  { name: "Bat", value: 0, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/zombiebat.png", slug: "zombiebat" },
  { name: "Snakebite Knife", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/snakebitek.png", slug: "snakebitek" },
  { name: "RIP", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/rip.png", slug: "rip" },
  { name: "Midnight", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/midnight.png", slug: "midnight" },
  { name: "Mummified", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/mummified.png", slug: "mummified" },
  { name: "Wrapped", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/wrappedgun.png", slug: "wrappedgun" },
  { name: "Indy", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/indy.png", slug: "indy" },
  { name: "Web", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/web.png", slug: "web" },
  { name: "Grave", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/graveg.png", slug: "graveg" },
  { name: "Choco", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/choco.png", slug: "choco" },
  { name: "Nutcracker", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/nutcracker.png", slug: "nutcracker" },
  { name: "Elderwood Blade", value: 0, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/elderwoodknife.png", slug: "elderwoodknife" },
  { name: "Monster", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/monster.png", slug: "monster" },
  { name: "Makeshift", value: 0, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/makeshift.png", slug: "makeshift" },
  { name: "Clan", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/clan.png", slug: "clan" },
  { name: "Haunted", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/hauntedk.png", slug: "hauntedk" },
  { name: "Blue Elite", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/eliteblue.png", slug: "eliteblue" },
  { name: "Tree Knife 2015", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/tree.png", slug: "tree" },
  { name: "Popsicle", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/popsicle-k-2023.png", slug: "popsicle-k-2023" },
  { name: "Coal", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/coal.png", slug: "coal" },
  { name: "Molten", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/molten.png", slug: "molten" },
  { name: "Ghost 2018", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghostk2018.png", slug: "ghostk2018" },
  { name: "Magma", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/magmak.png", slug: "magmak" },
  { name: "Sparkle9", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle9.png", slug: "sparkle9" },
  { name: "Sharky", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/sharky-k-2024.png", slug: "sharky-k-2024" },
  { name: "Spitfire", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/spitfire.png", slug: "spitfire" },
  { name: "Rupture", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/bleed.png", slug: "bleed" },
  { name: "Vampire", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/vampireg2018.png", slug: "vampireg2018" },
  { name: "Yellow", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/kool.png", slug: "kool" },
  { name: "Cane Gun", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/canegun.png", slug: "canegun" },
  { name: "Ghostly", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghostrbx-k-2022.png", slug: "ghostrbx-k-2022" },
  { name: "Eyeball", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/eyeball-k-2022.png", slug: "eyeball-k-2022" },
  { name: "Zombie Camo", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/greencamo-k-2022.png", slug: "greencamo-k-2022" },
  { name: "Survivor Camo", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/bluecamo-k-2022.png", slug: "bluecamo-k-2022" },
  { name: "Hunter", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/hunter-k-2022.png", slug: "hunter-k-2022" },
  { name: "Apocalypse", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/apoc-k-2022.png", slug: "apoc-k-2022" },
  { name: "Darkness", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/darkness-g-2022.png", slug: "darkness-g-2022" },
  { name: "Candied", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/candied-k-2022.png", slug: "candied-k-2022" },
  { name: "Stockings", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/stockings-k-2022.png", slug: "stockings-k-2022" },
  { name: "Mistletoe", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/mistletoe-k-2022.png", slug: "mistletoe-k-2022" },
  { name: "Snowman", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/snowman-g-2022.png", slug: "snowman-g-2022" },
  { name: "Vines", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/vines-g-2023.png", slug: "vines-g-2023" },
  { name: "Pumpkin", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/pumpkin-g-2023.png", slug: "pumpkin-g-2023" },
  { name: "Steel", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/steel-g-2023.png", slug: "steel-g-2023" },
  { name: "Leaves", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/leaves-k-2023.png", slug: "leaves-k-2023" },
  { name: "Eclipse", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/eclipse-k-2023.png", slug: "eclipse-k-2023" },
  { name: "Spearmint", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/spearmint-g-2025.png", slug: "spearmint-g-2025" },
  { name: "Wood", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/wood-k-2023.png", slug: "wood-k-2023" },
  { name: "Hazard", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/hazard-k-2022.png", slug: "hazard-k-2022" },
  { name: "Boney", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/bones-k-2022.png", slug: "bones-k-2022" },
  { name: "Glowy", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/glowy-k-2023.png", slug: "glowy-k-2023" },
  { name: "Moonlight", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/moonlight-g-2022.png", slug: "moonlight-g-2022" },
  { name: "Witchbrew", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/witch-k-2022.png", slug: "witch-k-2022" },
  { name: "Polar Bear", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/polarbear-k-2025.png", slug: "polarbear-k-2025" },
  { name: "Lantern", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/jack-k-2022.png", slug: "jack-k-2022" },
  { name: "Xeno", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/xeno-k-2025.png", slug: "xeno-k-2025" },
  { name: "Wreaths", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/wreaths-k-2024.png", slug: "wreaths-k-2024" },
  { name: "Wraith", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/wraith-k-2022.png", slug: "wraith-k-2022" },
  { name: "Witch&#x27;s Brew", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/witchbrew-k-2024.png", slug: "witchbrew-k-2024" },
  { name: "Watcher Knife 2021", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/watcher-k-2021.png", slug: "watcher-k-2021" },
  { name: "Watcher Gun 2021", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/watcher-g-2021.png", slug: "watcher-g-2021" },
  { name: "UFOs", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ufos-k-2025.png", slug: "ufos-k-2025" },
  { name: "Trees", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/trees-k-2020.png", slug: "trees-k-2020" },
  { name: "Treats", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/treats-k-2025.png", slug: "treats-k-2025" },
  { name: "Traveler", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/traveler-k-2023.png", slug: "traveler-k-2023" },
  { name: "Swirl", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/swirl-k-2021.png", slug: "swirl-k-2021" },
  { name: "Sweater Gun 2018", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/sweater-g-2018.png", slug: "sweater-g-2018" },
  { name: "Storm", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/storm-k-2024.png", slug: "storm-k-2024" },
  { name: "Stickers Gun", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/stickers-g-2021.png", slug: "stickers-g-2021" },
  { name: "Stars", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/stars-k-2023.png", slug: "stars-k-2023" },
  { name: "Starry", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/starry-k-2021.png", slug: "starry-k-2021" },
  { name: "Spectral", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/spectral-k-2021.png", slug: "spectral-k-2021" },
  { name: "Spectral Gun", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/spectral-g-2021.png", slug: "spectral-g-2021" },
  { name: "Snowman Knife 2018", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowman-k-2018.png", slug: "snowman-k-2018" },
  { name: "Snowglobe", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowglobe-k-2023.png", slug: "snowglobe-k-2023" },
  { name: "Snowflakes", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowflakes-k-2020.png", slug: "snowflakes-k-2020" },
  { name: "Snowfall", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowfall-k-2023.png", slug: "snowfall-k-2023" },
  { name: "Snowball", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/snowball-k-2025.png", slug: "snowball-k-2025" },
  { name: "Sleigh", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/sleigh-k-2024.png", slug: "sleigh-k-2024" },
  { name: "Slashed", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/slashed-k-2020.png", slug: "slashed-k-2020" },
  { name: "Skulls", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/skulls-k-2021.png", slug: "skulls-k-2021" },
  { name: "Etched", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/skull-k-2023.png", slug: "skull-k-2023" },
  { name: "Curse", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/runic-k-2022.png", slug: "runic-k-2022" },
  { name: "Ritual", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/ritual-g-2024.png", slug: "ritual-g-2024" },
  { name: "Ribbons", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ribbons-k-2021.png", slug: "ribbons-k-2021" },
  { name: "Ribbon", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ribbon-k-2023.png", slug: "ribbon-k-2023" },
  { name: "Reindeer", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/reindeer-k-2025.png", slug: "reindeer-k-2025" },
  { name: "PGSH", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/rbxscary-k-2023.png", slug: "rbxscary-k-2023" },
  { name: "Portal Knife", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/portal-k-2020.png", slug: "portal-k-2020" },
  { name: "Portal Gun", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/portal-g-2020.png", slug: "portal-g-2020" },
  { name: "Penguin", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/penguin-k-2025.png", slug: "penguin-k-2025" },
  { name: "Ornaments", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/ornaments-k-2025.png", slug: "ornaments-k-2025" },
  { name: "Mummy Knife 2020", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/mummy-k-2020.png", slug: "mummy-k-2020" },
  { name: "Mummy Gun 2020", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/mummy-g-2020.png", slug: "mummy-g-2020" },
  { name: "Moon", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/moon-k-2021.png", slug: "moon-k-2021" },
  { name: "Meltdown", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/meltdown-k-2023.png", slug: "meltdown-k-2023" },
  { name: "Logcutter", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/logcutter-k-2024.png", slug: "logcutter-k-2024" },
  { name: "Kraken", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/kraken-k-2024.png", slug: "kraken-k-2024" },
  { name: "Igloo", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/igloo-k-2024.png", slug: "igloo-k-2024" },
  { name: "Icedriller", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/icedriller-g-2020.png", slug: "icedriller-g-2020" },
  { name: "Icecracker", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/icecracker-k-2020.png", slug: "icecracker-k-2020" },
  { name: "Ice Camo", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/icecamo-g-2021.png", slug: "icecamo-g-2021" },
  { name: "Hot Chocolate", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/hotchocolate-k-2024.png", slug: "hotchocolate-k-2024" },
  { name: "Hologram", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/hologram-k-2025.png", slug: "hologram-k-2025" },
  { name: "Holly", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/holly-k-2018.png", slug: "holly-k-2018" },
  { name: "Gothic Knife", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/gothic-k-2021.png", slug: "gothic-k-2021" },
  { name: "Gothic", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/gothic-g-2021.png", slug: "gothic-g-2021" },
  { name: "Cookiecane", value: 0, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingermint-k.png", slug: "gingermint-k" },
  { name: "Gingermint", value: 0, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/gingermint-g.png", slug: "gingermint-g" },
  { name: "Gingerheart", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingerheart-k-2024.png", slug: "gingerheart-k-2024" },
  { name: "Gingercookie", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/gingercookie-k-2025.png", slug: "gingercookie-k-2025" },
  { name: "Ginger Knife 2018", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/ginger-k-2018.png", slug: "ginger-k-2018" },
  { name: "Ginger Gun 2018", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/ginger-g-2018.png", slug: "ginger-g-2018" },
  { name: "Giftwrap", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/giftwrap-k-2021.png", slug: "giftwrap-k-2021" },
  { name: "Gift Bag", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/giftbag-k-2020.png", slug: "giftbag-k-2020" },
  { name: "Wrap", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/gift-k-2020.png", slug: "gift-k-2020" },
  { name: "Ghosts", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghosts-k-2024.png", slug: "ghosts-k-2024" },
  { name: "Wraiths", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghosts-k-2021.png", slug: "ghosts-k-2021" },
  { name: "Ghostfire", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/ghostfire-g-2022.png", slug: "ghostfire-g-2022" },
  { name: "Ghastly", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/ghastly-k-2023.png", slug: "ghastly-k-2023" },
  { name: "Frostflame", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/frostflame-k-2024.png", slug: "frostflame-k-2024" },
  { name: "Frosted", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/frosted-k-2019.png", slug: "frosted-k-2019" },
  { name: "Forest", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/forest-g-2024.png", slug: "forest-g-2024" },
  { name: "Fireplace", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/fireplace-k-2023.png", slug: "fireplace-k-2023" },
  { name: "Fall Camo", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/fallcamo-g-2021.png", slug: "fallcamo-g-2021" },
  { name: "Fall", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/fall-g-2025.png", slug: "fall-g-2025" },
  { name: "Watcher Knife 2020", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/eyes-k-2020.png", slug: "eyes-k-2020" },
  { name: "Eyes", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/eyes-g-2025.png", slug: "eyes-g-2025" },
  { name: "Watcher", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/eyes-g-2020.png", slug: "eyes-g-2020" },
  { name: "Energized", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/energized-k-2025.png", slug: "energized-k-2025" },
  { name: "Darkknife", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/dark-k-2023.png", slug: "dark-k-2023" },
  { name: "Darkgun", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/dark-g-2023.png", slug: "dark-g-2023" },
  { name: "Cursed", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/cursed-k-2024.png", slug: "cursed-k-2024" },
  { name: "Cracks", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/cracks-k-2021.png", slug: "cracks-k-2021" },
  { name: "Cookie", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/cookie-k-2021.png", slug: "cookie-k-2021" },
  { name: "Nightstar", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/constellation-k-2024.png", slug: "constellation-k-2024" },
  { name: "Nightsky", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/constellation-g-2024.png", slug: "constellation-g-2024" },
  { name: "Clown", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/clown-g-2024.png", slug: "clown-g-2024" },
  { name: "Cat Gun", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/cat-g-2021.png", slug: "cat-g-2021" },
  { name: "Carved Knife", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/carved-k-2020.png", slug: "carved-k-2020" },
  { name: "Carved", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/carved-g-2020.png", slug: "carved-g-2020" },
  { name: "Canes", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/canes-k-2023.png", slug: "canes-k-2023" },
  { name: "Candy Swirl Gun", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/candyswirl-g-2019.png", slug: "candyswirl-g-2019" },
  { name: "Candy Corn Gun 2020", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/candycorn-g-2020.png", slug: "candycorn-g-2020" },
  { name: "Candles", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/candles-k-2024.png", slug: "candles-k-2024" },
  { name: "Candle", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/candle-k-2020.png", slug: "candle-k-2020" },
  { name: "Bells", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/bells-k-2023.png", slug: "bells-k-2023" },
  { name: "Aurora Knife 2021", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/aurora-k-2021.png", slug: "aurora-k-2021" },
  { name: "Arctic", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/arctic-k-2022.png", slug: "arctic-k-2022" },
  { name: "Aliens", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/aliens-g-2021.png", slug: "aliens-g-2021" },
  { name: "Abduction", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/abduction-k-2025.png", slug: "abduction-k-2025" },
  { name: "Balloons", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/waterballoons-g-2024.png", slug: "waterballoons-g-2024" },
  { name: "Turtle", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/turtle-k-2024.png", slug: "turtle-k-2024" },
  { name: "Striped", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/striped-g-2025.png", slug: "striped-g-2025" },
  { name: "Starfish", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/starfish-g-2024.png", slug: "starfish-g-2024" },
  { name: "Soda", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/soda-g-2025.png", slug: "soda-g-2025" },
  { name: "Skyline", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/skyline-k-2025.png", slug: "skyline-k-2025" },
  { name: "Scarf", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/scarf-k-2023.png", slug: "scarf-k-2023" },
  { name: "Sandy", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/sandy-g-2024.png", slug: "sandy-g-2024" },
  { name: "Jellyfish", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/jellyfish-k-2024.png", slug: "jellyfish-k-2024" },
  { name: "Floatie", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/floatie-g-2024.png", slug: "floatie-g-2024" },
  { name: "Coconut", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/coconut-k-2025.png", slug: "coconut-k-2025" },
  { name: "Clownfish", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/clownfish-k-2024.png", slug: "clownfish-k-2024" },
  { name: "Aquarium", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/aquarium-g-2025.png", slug: "aquarium-g-2025" },
  { name: "Chromatic", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/chromatic-g-2023.png", slug: "chromatic-g-2023" },
  { name: "Broken", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/broken-k-2023.png", slug: "broken-k-2023" },
  { name: "Retro", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/retro-k-2025.png", slug: "retro-k-2025" },
  { name: "Pop Art", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/popart-k-2025.png", slug: "popart-k-2025" },
  { name: "Pool", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/pool-k-2025.png", slug: "pool-k-2025" },
  { name: "Meadow", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/meadow-g-2025.png", slug: "meadow-g-2025" },
  { name: "Lava", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/lava-k-2025.png", slug: "lava-k-2025" },
  { name: "Tropical", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/tropical-k-2025.png", slug: "tropical-k-2025" },
  { name: "Dolphins", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/dolphins-k-2025.png", slug: "dolphins-k-2025" },
  { name: "Chick", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/chick-k-2025.png", slug: "chick-k-2025" },
  { name: "Carrots", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/carrots-k-2025.png", slug: "carrots-k-2025" },
  { name: "Bunnies", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/bunnies-k-2025.png", slug: "bunnies-k-2025" },
  { name: "Palms", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/palms-g-2024.png", slug: "palms-g-2024" },
  { name: "Floral", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/floral-g-2024.png", slug: "floral-g-2024" },
  { name: "Spring", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/spring-k-2024.png", slug: "spring-k-2024" },
  { name: "Robot", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/robot-k-2024.png", slug: "robot-k-2024" },
  { name: "Rainbow Gun", value: 0, rarity: "godly", type: "gun", image: "https://cdn.bloxluck.com/item-images/rainbow-g.png", slug: "rainbow-g" },
  { name: "Bio", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/bio-k-2023.png", slug: "bio-k-2023" },
  { name: "Rainbow", value: 0, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/rainbow-k.png", slug: "rainbow-k" },
  { name: "Nuke", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/nuke-g-2023.png", slug: "nuke-g-2023" },
  { name: "Sakura", value: 0, rarity: "godly", type: "knife", image: "https://cdn.bloxluck.com/item-images/sakura-k.png", slug: "sakura-k" },
  { name: "Painted", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/painted-k-2023.png", slug: "painted-k-2023" },
  { name: "Abstract", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/abstract.png", slug: "abstract" },
  { name: "Toy", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/toy-g-2023.png", slug: "toy-g-2023" },
  { name: "Nether", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/nether.png", slug: "nether" },
  { name: "Love", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/love.png", slug: "love" },
  { name: "Sidewinder", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sidewinder.png", slug: "sidewinder" },
  { name: "Circuit", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/circuit.png", slug: "circuit" },
  { name: "Splatter", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/splatter.png", slug: "splatter" },
  { name: "Decorated", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/decorated-k-2025.png", slug: "decorated-k-2025" },
  { name: "Sunny", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/sunny-g-2025.png", slug: "sunny-g-2025" },
  { name: "Wooden", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/wooden.png", slug: "wooden" },
  { name: "Wanwood", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/wanwood.png", slug: "wanwood" },
  { name: "News", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/news.png", slug: "news" },
  { name: "Green", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/marley.png", slug: "marley" },
  { name: "Linked", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/linked.png", slug: "linked" },
  { name: "HL2", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/hl2.png", slug: "hl2" },
  { name: "Engraved", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/engraved.png", slug: "engraved" },
  { name: "Eco", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/eco.png", slug: "eco" },
  { name: "Combat II", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/combat2.png", slug: "combat2" },
  { name: "Cardboard", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/cardboard.png", slug: "cardboard" },
  { name: "Borders", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/borders.png", slug: "borders" },
  { name: "Static", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/static.png", slug: "static" },
  { name: "Sketch", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/sketch.png", slug: "sketch" },
  { name: "Pirate", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/pirate.png", slug: "pirate" },
  { name: "Brown", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/pepper.png", slug: "pepper" },
  { name: "Nova", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/nova.png", slug: "nova" },
  { name: "Missing", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/missing.png", slug: "missing" },
  { name: "Krypto", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/krypto.png", slug: "krypto" },
  { name: "iRevolver", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/irevolver.png", slug: "irevolver" },
  { name: "Donut", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/donut.png", slug: "donut" },
  { name: "Black", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/dew.png", slug: "dew" },
  { name: "Checker", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/checker.png", slug: "checker" },
  { name: "Brush", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/brush.png", slug: "brush" },
  { name: "Ace", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/ace.png", slug: "ace" },
  { name: "8bit", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/8bit.png", slug: "8bit" },
  { name: "Stainless", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/stainless.png", slug: "stainless" },
  { name: "Sparkle10", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle10.png", slug: "sparkle10" },
  { name: "Whiteout", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/whiteout.png", slug: "whiteout" },
  { name: "Vortex", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/vortex.png", slug: "vortex" },
  { name: "Pumpkin Pie", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/pumpkinpie-k-2023.png", slug: "pumpkinpie-k-2023" },
  { name: "Splash", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/splash.png", slug: "splash" },
  { name: "Red", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/snoop.png", slug: "snoop" },
  { name: "Musical", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/musical.png", slug: "musical" },
  { name: "Hive", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/hive.png", slug: "hive" },
  { name: "Hardened", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/hardened.png", slug: "hardened" },
  { name: "Spectrum", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/spectrum.png", slug: "spectrum" },
  { name: "Korblox", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/korblox.png", slug: "korblox" },
  { name: "Infiltrator", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/infiltrator.png", slug: "infiltrator" },
  { name: "Imbued", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/imbued.png", slug: "imbued" },
  { name: "Ice", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/ice.png", slug: "ice" },
  { name: "Future", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/future.png", slug: "future" },
  { name: "Hacker", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/hacker.png", slug: "hacker" },
  { name: "Juice", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/aid.png", slug: "aid" },
  { name: "Universe", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/universe.png", slug: "universe" },
  { name: "Squire", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/squire.png", slug: "squire" },
  { name: "Pool Noodle", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/noodle-k-2023.png", slug: "noodle-k-2023" },
  { name: "Hazmat", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/hazmat.png", slug: "hazmat" },
  { name: "Bluesteel", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/bluesteelgun.png", slug: "bluesteelgun" },
  { name: "Bit", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/bit.png", slug: "bit" },
  { name: "Big Kill", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/bigkill.png", slug: "bigkill" },
  { name: "Aqua", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/aqua.png", slug: "aqua" },
  { name: "Lucky", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/lucky.png", slug: "lucky" },
  { name: "Predator", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/predatorknife.png", slug: "predatorknife" },
  { name: "Overseer", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/overseerknife.png", slug: "overseerknife" },
  { name: "Shiny", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/mlg.png", slug: "mlg" },
  { name: "Fusion", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/fusion.png", slug: "fusion" },
  { name: "Fade", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/fade.png", slug: "fade" },
  { name: "Viper", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/viper.png", slug: "viper" },
  { name: "Sparkle", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/sparkle.png", slug: "sparkle" },
  { name: "Star", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/star.png", slug: "star" },
  { name: "Plasmite", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/plasmite.png", slug: "plasmite" },
  { name: "Log", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/log.png", slug: "log" },
  { name: "Pink", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/lmfao.png", slug: "lmfao" },
  { name: "Grind", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/grind.png", slug: "grind" },
  { name: "Galaxy", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/galaxy.png", slug: "galaxy" },
  { name: "Galactic", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/galactic.png", slug: "galactic" },
  { name: "Fallout", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/fallout.png", slug: "fallout" },
  { name: "Euro", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/euro.png", slug: "euro" },
  { name: "Iron", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/iron.png", slug: "iron" },
  { name: "Fragile", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/fragile-g-2023.png", slug: "Fragile_G_2023" },
  { name: "Purple", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/doritos.png", slug: "doritos" },
  { name: "Cold", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/cold.png", slug: "cold" },
  { name: "Sun", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/sunset-g-2023.png", slug: "sunset-g-2023" },
  { name: "High Tech", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/hightech.png", slug: "hightech" },
  { name: "Biogun", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/biogun.png", slug: "biogun" },
  { name: "Splash Gun", value: 0, rarity: "legendary", type: "gun", image: "https://cdn.bloxluck.com/item-images/splash-g.png", slug: "splash-g" },
  { name: "Sparkle8", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle8.png", slug: "sparkle8" },
  { name: "Sparkle7", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle7.png", slug: "sparkle7" },
  { name: "Sparkle5", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle5.png", slug: "sparkle5" },
  { name: "Sparkle3", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle3.png", slug: "sparkle3" },
  { name: "Sparkle2", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle2.png", slug: "sparkle2" },
  { name: "RB Knife", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/rbknife.png", slug: "rbknife" },
  { name: "Pea", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/pea.png", slug: "pea" },
  { name: "Cherry", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/cherry.png", slug: "cherry" },
  { name: "Cheddar", value: 0, rarity: "uncommon", type: "gun", image: "https://cdn.bloxluck.com/item-images/cheddar.png", slug: "cheddar" },
  { name: "Splat", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/splat.png", slug: "splat" },
  { name: "Slate", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/slate.png", slug: "slate" },
  { name: "Orange", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/fanta.png", slug: "fanta" },
  { name: "Emerald", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/emerald.png", slug: "emerald" },
  { name: "Deep Sea", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/deepsea.png", slug: "deepsea" },
  { name: "Xbox", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/xbox.png", slug: "xbox" },
  { name: "Shaded", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/shaded.png", slug: "shaded" },
  { name: "Rune", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/rune.png", slug: "rune" },
  { name: "Nightfire", value: 0, rarity: "rare", type: "gun", image: "https://cdn.bloxluck.com/item-images/nightfire.png", slug: "nightfire" },
  { name: "Marble", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/marble-k-2023.png", slug: "Marble_K_2023" },
  { name: "Lovely", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/lovely.png", slug: "lovely" },
  { name: "Graffiti", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/graffiti.png", slug: "graffiti" },
  { name: "Copper", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/copper.png", slug: "copper" },
  { name: "Combat", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/combat.png", slug: "combat" },
  { name: "Clown Gun", value: 0, rarity: "common", type: "gun", image: "https://cdn.bloxluck.com/item-images/clown-g.png", slug: "clown-g" },
  { name: "Space", value: 0, rarity: "rare", type: "knife", image: "https://cdn.bloxluck.com/item-images/space.png", slug: "space" },
  { name: "Leaf", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/leaf.png", slug: "leaf" },
  { name: "Elite", value: 0, rarity: "legendary", type: "knife", image: "https://cdn.bloxluck.com/item-images/elite.png", slug: "elite" },
  { name: "Tiger", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/tiger.png", slug: "tiger" },
  { name: "Sparkle1", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle1.png", slug: "sparkle1" },
  { name: "Sparkle6", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle6.png", slug: "sparkle6" },
  { name: "Sparkle4", value: 0, rarity: "common", type: "knife", image: "https://cdn.bloxluck.com/item-images/sparkle4.png", slug: "sparkle4" },
  { name: "Rose", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/rose-k-2023.png", slug: "Rose_K_2023" },
  { name: "Gifted", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/gifted.png", slug: "gifted" },
  { name: "Cheesy", value: 0, rarity: "uncommon", type: "knife", image: "https://cdn.bloxluck.com/item-images/cheesy.png", slug: "cheesy" },
];
